### ISSUE TITLE
Define dates for SPS17

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/sps17#1]
This requires us to define:
-  How long? 
-  Once again a one track one day conference?

Fight!

**Comment by dbrgn** [comment]
I'd say the same as last time :)

**Comment by ghost** [comment]
Hi everyone, 

I've received email from Karolina:

> And you may also want to participate to the swiss python summit association constituent meeting... (6th july in Zurich)

I would love to attend. Where can I find more details? It seems that place and date are not defined yet. 
Could you please clarify?
Cheers!

**Comment by ccdesales** [comment]
Hi Frantisek.

The constituent meeting will take place on Wednesday the 6th of July at Webrepublic AG (Seefeldstrasse 233, 8008 Zürich). You'll be most welcome to join.

We've sent an email to everyone who attended the conference last year, but given we have place for max. 20 people for the meeting I doubt it's a good idea to promote it.

**Comment by bkarolina** [comment]
Could you also please write a time when this meeting begins? Thanks.

**Comment by href** [comment]
The meeting begins at 19:00.

**Comment by ccdesales** [comment]
Probably same as las time since we are bound to the semester breaks.

**Comment by dbrgn** [comment]
See discussion in #2.
