### ISSUE TITLE
Promote Call for proposals

### ISSUE THREAD

**Issue by cdesales** [SwissPy/sps17#11]
- [x] Pycoders newsletter: www.pycoders.com
- [x] PythonWeekly newsletter www.pythonweekly.com
- [ ] Python email list
- [x] Reddit
- [x] Twitter
- [ ] Posters in Swiss universities and hacker spaces
- [ ] Zürich Web Tuesday
- [ ] Hackernews

See: https://github.com/SwissPy/swisspycon/issues/18

**Comment by href** [comment]
So, are we ready to promote the CFP properly?

**Comment by ccdesales** [comment]
> So, are we ready to promote the CFP properly?

Yes, we are ready for it.

**Comment by href** [comment]
Posted it on reddit, please upvote: https://www.reddit.com/r/Python/comments/51w8st/the_swiss_python_summit_2017_is_looking_for/

**Comment by The-Compiler** [comment]
I also submitted it to the [Linux Weekly Newsletter calendar](https://lwn.net/Calendar/).

**Comment by href** [comment]
It's on Techup.ch as well now: http://techup.ch/2369/swiss-python-summit-2017

**Comment by sfkeller** [comment]
@href: Just FYI: Techup.ch events are republished by ICT-Agenda: http://ict-agenda.ch/events/swiss-python-summit-2017

Other info & question: I'd like to announce a proposal from my institute most probably about this project https://twitter.com/murthy_10/status/771319216175710209 . Do you/we have enough proposals? 

If not, we could use more channels, e.g. http://www.ossdirectory.com/oss-events/

**Comment by ccdesales** [comment]
All proposals are welcome. Right now we don't really have many proposals.

**Comment by href** [comment]
@sfkeller Thanks, that's actually nice :)

Please do submit a proposal, the more we get, the better the final selection.

**Comment by dbrgn** [comment]
Yes, a talk about that would be great :)

**Comment by sfkeller** [comment]
Murthy and me both submitted a paper. 
BTW: Where do you manage the proposals? Is there a Google Docs directory?

**Comment by href** [comment]
Since the call for proposals is over I'm closing this one.
