### ISSUE TITLE
Design Print Materials

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#12]
We need a new set of posters. Aside from the logo we're pretty free in how we do them, so if anyone wants to do some graphic design, go ahead. Nothing fancy required.

Posters:
- [x] Event Poster (Where, When, What, Who, Why)
- [ ] Event Badge (With space for name and company)
- [ ] Staff T-Shirt
- [ ] Directions for the Event (Left, Straight, Right Arrow with Logo)
- [ ] Template where we can put things like "Registration" or "Jobwall"

Format:

PDF, A3, A4

The logo and last years posters can be found here:

https://github.com/SwissPy/SwissPy.github.io/tree/source/content/images

I did this last year, so I'm happy to help out, but I'd be thrilled if someone new started doing this :)

Note:

Sponsors will want their logo on those posters. So have some space for that.

**Comment by bkarolina** [comment]
I would like to take this. And some help/advice/guidance will be appreciated ;-) 
I suppose that event poster should be done asap? (if we want to spread them at universities?).

**Comment by dbrgn** [comment]
I think @href already did one, but I think it wouldn't hurt if we have another design.

@bkarolina why don't you create one without having seen Denis' poster? then we get more new ideas :)

**Comment by href** [comment]
Actually I just created one possible event poster yesterday :) - I'm waiting for the logos of our sponsors before publishing it. [I posted a sneak-peak in the chat yesterday](https://swiss-python-summit.slack.com/files/href/F2FM48RQX/screenshot_of_sketch__25-09-16_15-03-51_.png).

But I'm not married to my poster, so feel free to create your own. We can have multiple designs or chose one out of many. The help for the rest of the prints is appreciated as well, though we don't have to do this so soon.

In any case I'm still gathering all the logos. Once I have them I'll post them here and then we can start cracking!

**Comment by bkarolina** [comment]
I didn't notice it :-O But acutally I like the text of the poster @href :-) 
Anyway, I can try to do another design of the poster. Or just help with the rest of the prints. I'll let you know this week whether I succeed with another poster design.

**Comment by dbrgn** [comment]
We should also have a flyer design. Or do we already have promotional flyers?

**Comment by href** [comment]
We do not. I'm not sure how effective flyers are, unless we hand them out somewhere? But I'm okay with one in principle. We'd have to print them professionally though - the posters can be printed at home.

**Comment by dbrgn** [comment]
Hm, true. I'm also not sure how to distribute the flyers. And regarding the budget, maybe @chiesax knows more now that we already have 3 sponsors.

**Comment by href** [comment]
Ok, we are ready to get cracking. I got the logos of all our sponsors. I only have dark on light logos at this point. I'm not sure we can get the inverse for everyone. If we need it I'll ask.

The logos of the sponsors as well as our own logo is here:
https://github.com/SwissPy/sps17/tree/master/resources

The font used in our logo as well as on all previous posters is Open Sans. I suggest we stick with it as it's quite versatile and suits us well. Plus it's free to use.

Keep in mind that 4teamwork gets the biggest logo. I'm not sure how to effectively be fair about this, but I think it should visually be clear who belongs to which tier. This is what I'm currently aiming for, though I will probably work on this some more over the weekend:

![screenshot of sketch 29-09-16 20-03-12](https://cloud.githubusercontent.com/assets/273163/18966072/2b336d86-8680-11e6-979f-e59a937255bc.png)

With the logos we have to make our sponsors happy and not feel cheated, so we need to be considerate of their use.

**Comment by chiesax** [comment]
Well, I will come back to you with a new version of the budget. But the calculation is quite easy. We basically have 2500CHF to spend. Question is how?

**Comment by href** [comment]
Looks like vshn is going to be a silver sponsor, which will complicate the design somewhat as we need to add a single smaller logo at the bottom or so. If we gain three silver sponsors that works better.

**Comment by href** [comment]
Heads up, the current 4teamwork logo's colors were slightly off. If you used it anywhere already get the fixed svg from the repository.

**Comment by href** [comment]
I created a first promotional poster that I think we can hang up: https://github.com/SwissPy/sps17/blob/master/resources/prints/promotion.pdf

Let me know if I should change anything.

**Comment by ccdesales** [comment]
Looks good to me. Do they fir in an A4 sheet? 

Does someone have an idea where to hang the posters?

**Comment by href** [comment]
Yeah, default is A4, but you can scale it up.

**Comment by ccdesales** [comment]
I guess we can consider this done. If any one needs the link it's in the repo, or in the list of closed issues.

**Comment by href** [comment]
Actually we need more posters later, see ticket description ;)
Maybe a more ample description would be print materials.

**Comment by sfkeller** [comment]
Dear all, dear @href : 
I just got the task from @dbrgn to print the poster and stick it at HSR.
Nice design - as always :-) But is it possible to add the HSR logo to the design material? This can be smaller than others. But I think even if the rooms are paid there's still some sponsoring from HSR and definitely a strong support from my lab!

**Comment by href** [comment]
@sfkeller

We're okay with having HSR as a silver sponsor (same logo size as vshn). We will waive your fee for it. It's in our interest, because it would result in an even number of logos which is easier to handle ;)

Plus we'll sure appreciate it to be able to lean on the same kind of support you offered us last time.

I'll update the poster within the next few days. I'll also add the logo to the website and tweet about it having HSR as a silver sponsor, unless you don't want that.

**Comment by sfkeller** [comment]
Hi @href: Thanks! 
I'll be able to plot several copies of poster (A0). One to be sticked at HSR main entry hall - and additional ones for your disposal: How many copies should I plot (then: to whom may I send them)?

**Comment by href** [comment]
@sfkeller 

The promotional poster has been [updated with HSR's logo](https://github.com/SwissPy/sps17/blob/master/resources/prints/promotion.pdf). It can also be found [on the website](http://www.python-summit.ch/#sponsors) now.

Is there an official HSR twitter account I can address our sponsorship announcement to?
It'll look like this: https://twitter.com/pythonsummit/status/784302250445246464

**Comment by sfkeller** [comment]
You can refer to this Twitter account: "HSR_Informatik".

**Comment by chiesax** [comment]
Hi, could you send me 3xA3 and 2xA2 posters to hang them at EPFL please?

**Comment by The-Compiler** [comment]
I got the A0 poster from @sfkeller, but no way to fit this anywhere in the HSR, it's just way too big!

I'd suggest I hang up the A0 one at the CCCZH hackerspace (@dbrgn what about coredump?), and we hang A3 posters at various locations at HSR:
- Building 4 near the Sekretriat (they asked for two, one for building 1 somewhere?)
- Building 1 at the Informatik-wall
- Building 1 at the VSHSR-Wandzeitung

So @sfkeller, could you print 4xA3 for the HSR? Maybe A2 for the Informatik-wall would work too, but anything bigger seems overkill.

**Comment by chiesax** [comment]
Would be great if someone could stick some posters at ETHZ too...

**Comment by dbrgn** [comment]
I can hang one up at Coredump, but A0 is a bit big. What about A1?

**Comment by sfkeller** [comment]
So I'll print 5 x A3.
What about postcards? This format would be convenient to be distributed at hacker and other IT events.

**Comment by dbrgn** [comment]
Yes, flyers wouldn't be too bad.

**Comment by chiesax** [comment]
I think we need at least 8 A3 posters: 4 for Florian, 1 for Danilo and 3 for myself.

**Comment by href** [comment]
@bkarolina Do you want to take a stab at postcards? It'll be at least a week until I have the time.

**Comment by bkarolina** [comment]
Yes, I would like to. But can you tell me how it should like (what it should contain etc) as I am not familiar with a concept of event's postcard.

**Comment by href** [comment]
It needs to contain the following:
- What
- Where
- When
- Website
- Sponsor Logos

Other than that you are pretty free. Ideally you use the sponsor logos more or less the way I did, because we have an obligation to have the them in these sizes (relative to each other).

**Comment by dbrgn** [comment]
> I am not familiar with a concept of event's postcard

That's just the format. It's meant as an A5 or A6 flyer, right?

**Comment by href** [comment]
I'd say A6 in this case. A5 is a bit big. Big enough to contain the my A4 poster in fact. A6 is too small, so we need something new.

**Comment by sfkeller** [comment]
I've delivered 4 A3 posters to Florian. There's 1 left for @dbrgn and 3 for @chiesax : Can you tell me the postal addresse where I can send them to?

**Comment by The-Compiler** [comment]
[x] 4 posters deployed at HSR :wink:

**Comment by sfkeller** [comment]
[x] 3 posters A3 send by snail mail to @chiesax .
[_] 3 posters A3 left on my desk to be delivered to whom :wink: ?

**Comment by dbrgn** [comment]
@sfkeller somehow I got an A0 poster, which is way too big for my use. did they get mixed up?

**Comment by chiesax** [comment]
Thx @sfkeller got them.

**Comment by sfkeller** [comment]
@dbrgn Ok. Then let's try another time: Can you send your colleage once again to my office in order to replace the A0 poster with the 3 posters A3? He can just show up during office hours.

**Comment by bkarolina** [comment]
Hi all, I have some draft of the postcard (nevertheless I have some problem with one logo of sponsors). I am travelling for short vacation in a few minutes and I'll be back on Tuesday evening. So, I believe that on Wednesday I can post it here.

**Comment by bkarolina** [comment]
Hi all,
this is only a draft (as I still have some problems with logos, to be more specific I have problem with logo of 4teamwork, I still get only "4" as a picture). And I am still in a quite hurry these days.

The empty space suppose to be a place for logos. Can you give me some feedback?

[postcard_good.pdf](https://github.com/SwissPy/sps17/files/566891/postcard_good.pdf)

**Comment by href** [comment]
I like it! It passes min_geek_factor. The only thing I've noticed is the SPS logo, which seems slightly skewed. Or am I imagining things?

**Comment by bkarolina** [comment]
@href it is really possible that it is skewed. In the final version I'll check it.

**Comment by sfkeller** [comment]
Nice. Do we have the appropriate credentials to use the Monty Python Flying Circus image? I seldomly check this; but in this case of a postcard this seems neccessary to me.

**Comment by jakeret** [comment]
I like the concept! Sweet
The spacing on the left, right, top and bottom is not the same for the images and the text. Either it should be aligned or completley different (maybe vertical centering of the right image)

**Comment by sfkeller** [comment]
@bkarolina Very important detail: Pls. write "Rapperswil" (not "Rapperswill"). See e.g. http://osm.org/go/0C0kY0xUs--?m= or http://demo.f4map.com/#lat=47.2235026&lon=8.8165333&zoom=18&camera.phi=-8.021

**Comment by bkarolina** [comment]
@sfkeller thank you, I didn't notice this mispell. Second, I'll try to check how it is works with he appropriate credentials to use the Monty Python Flying Circus image. I have never done that so I hope that I'll find solution for this.

**Comment by bkarolina** [comment]
Hi guys,  here is a final version of the postcard (I hope now is everything alright - with formatting, (mis)spelling, etc).
I've downloaded a picture of the foot from Wikipedia -- I think it should be alright, regarding credentials. I didn't know that the foot comes from the painting from the 16th century, so I really believe this should not be a problem :-)
 
[summit_postcard.pdf](https://github.com/SwissPy/sps17/files/608610/summit_postcard.pdf)

**Comment by href** [comment]
I've added the staff t-shirt to the print materials to be produced. The t-shirts should be ordered this month.

Also a note about the badges. We discussed in the chat before to have a personal and a company badge. The badges would still stay anonymous, that is everyone writes in their name at the conference. To avoid last year's delivery problems with the sleeves we'll have to order fitting sleeves and lanyards this month also.

@sfkeller Can we count on you again to print the badges on thick paper before the conference?

**Comment by sfkeller** [comment]
> @sfkeller Can we count on you again to print the badges on thick paper before the conference?

Yes.

**Comment by href** [comment]
Any suggestions about where to print the t-shirt?

**Comment by dbrgn** [comment]
We got them from Spreadshirt (DE) last time. I liked the quality (B&W only though). VAT needs to be paid though.

**Comment by The-Compiler** [comment]
I recently ordered 100 [B&C exact shirts](http://www.textil-grosshandel.eu/b-c-t-shirt-exact-190.html) at Textil-Großhandel - many mentioned they love the quality.

They offer various [printing methods](http://www.textil-grosshandel.eu/textildruck/), but you'll need to get at least 10 shirts.

**Comment by bkarolina** [comment]
I have question about postcard -- they will be distributed direct at the conference or what is its destiny? (I am sorry about this stupid question, but I am still not familiar with concept of postcard). 
And if they needed to be printed, should I take care of it? Or do you any suggestion where they can be printed?

T-Shirt --> I like @The-Compiler suggestion. I always prefer shop with some personal recommendations. So if the T-Shirt are good quality then it is perfect. 
Printing methods -- I believe we will have at least 10 shirts, right?

**Comment by href** [comment]
I think the postcard is meant to be handed out in an on-demand basis. E.g. if anyone of us goes to a talk we can print the postcard beforehand and then hand it out. I'm not sure how much sense it makes to print them professionally now and then hand it out to all members.

I'd say we'll have somewhere between 10 and 20 shirts. Though our budget actually has room for 30 shorts for 14.- each. Maybe we could do a shirt without a "staff" notice and also hand them out to the speakers? Then we'd reach 30.

**Comment by chiesax** [comment]
I agree to give a shirt to the speakers...

**Comment by bkarolina** [comment]
Yes, I like this ideas as well.

**Comment by The-Compiler** [comment]
FWIW make sure to make some calculations first - for example, when you need ~30 with silkscreen printing (which is what I went with), ordering 50 is actually cheaper because the shirts are cheap (2.61€ per shirt for the one I linked), and the printing is much cheaper (silkscreen with 1 color: 2.47€ per shirt starting with 50, 5.48€ per shirt for 20-49).

> Though our budget actually has room for 30 shorts for 14.- each. 

[They can do that too](http://www.textil-grosshandel.eu/fruit-of-the-loom-classic-boxer-2er-pack.html) (SCNR!)

**Comment by href** [comment]
I think we should actually go with @The-Compiler's suggestion, and order a very simple print like the following from Text-Großhandel:

![screenshot of sketch 02-01-17 11-41-00](https://cloud.githubusercontent.com/assets/273163/21587782/67ed7dd4-d0e0-11e6-9149-9f03caba9529.png)

What do ya'll think? I personally wouldn't add any "Staff" text or anything like that. We can simply tell people that the ones wearing the shirt are helpers. It'll also be somewhat obvious since everyone at reception will wear one.

**Comment by dbrgn** [comment]
:+1:

**Comment by href** [comment]
You weren't kidding with ordering a larger amount @The-Compiler. I'm about to order 50 shirts for less than if I ordered 30. Including import it'll clock in around 350.- including shipping and import taxes, which is well below our 420.- budget and includes a good number of shirts:

![screenshot of safari 03-01-17 19-44-54](https://cloud.githubusercontent.com/assets/273163/21618833/2a45dcf2-d1ed-11e6-87c2-70a3d3d6b24f.png)

**Comment by href** [comment]
I have the quote for the print. Unfortunately it's a bit higher than expected. The shirts themselves plus printing comes up to 326.20€. In addition to that there seems to be 18€ shipping and an estimated 62.60CHF in import taxes.

This totals to an amount of 431.01CHF. This is not much over budget, but it means we have no extra money left for the lanyard/sleeves. Though we are less over budget there than I initially thought.

In any case, I think it's a good deal and the shop leaves a decent impression. So unless I hear any objections I'll go ahead and wire them the money later tonight. This will grant me an example print which I get as a foto. Once that's okay the order should be shipping in about 1-2 weeks.

If the 100+ bucks we're over budget in the printing department are a problem I'm sure we can find a solution.

**Comment by The-Compiler** [comment]
> This will grant me an example print which I get as a foto.

If you mean the "Korrekturabzug", that's simply a PDF with the graphic they got imported in their tool. Think of it as a mockup. Not a real print. Saved my ass with mine though as my file was subtly corrupted and got cut off in their import.

You can order a sample print (and IIRC not pay much extra if you actually end up ordering), but I didn't do that for mine. Also, not sure how long the whole roundtrip takes.

**Comment by href** [comment]
I see, thanks. I won't be going for the sample print. I don't think we have that kind of time.

How long did it take them to send it to you after payment @The-Compiler?

**Comment by The-Compiler** [comment]
Don't remember exactly - I ordered them to a friends place in Germany and meeting there was the bottleneck. I think they were quite fast though.

**Comment by href** [comment]
We got the shirts ready.
