### ISSUE TITLE
Answer Calls for Proposal E-Mails, Manage Speakers

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#13]
It would be awesome if we could have someone be the single contact for all speakers. That would include answering to their initial proposal, let them know the result once we have voted and welcoming them on the day of the conference.

Part of this job would also be to keep track of the proposals and later the speakers and making sure they show up on time.

This can technically be done by multiple people, but I feel it adds a personal touch if someone does this singlehandedly. At this stage this shouldn't be too much work.

Speak up if that sounds like this is up your ally!

**Comment by bkarolina** [comment]
I can be a contact for all speakers.

**Comment by href** [comment]
Great! I'll send you an e-mail to give you access to info@python-summit.ch. Then, once we are in progress with https://github.com/SwissPy/sps17/issues/11, I'll trust you to manage the incoming proposals 👍

**Comment by dbrgn** [comment]
:sparkles:

**Comment by dbrgn** [comment]
@bkarolina I assigned you to the "Speaker communications & coordination" item at #4.

**Comment by jakeret** [comment]
I was trying to find the response email from last year so that we don't have to rewrite it. But I couldn't find it on GitHub. Maybe it's somewhere in the outbox on the mail server

**Comment by href** [comment]
Actually we don't seem to have sent one. At least I can't find one in the outbox. There's registration confirmation and post-speaker selection e-mails, but no "thank you for your proposal" mails, as far as I can tell.

**Comment by ccdesales** [comment]
@bkarolina this is a heads up. Today I'm starting promotion of our CFP and there most likely be new entries which will need confirmation from you. 

Kindly provide a Gmail address so I can grant you access to the spreadsheet.

**Comment by bkarolina** [comment]
Hi, thanks for heads up. My e-mail address is karolina.bzdusek (at) gmail.com

**Comment by ccdesales** [comment]
@bkarolina I've shared the spreadsheet with you. Feel free to delete the comment with your email address now.

**Comment by href** [comment]
I'll close this ticket, since this position has been filled.
