### ISSUE TITLE
Setup and Handle Registration

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#14]
This job includes setting up a registration form using whatever you prefer (we previously used google forms, but anything goes) and keeping track of signups.

The person doing this should ensure that we can fit all people that are signed up, keep track of cancellations and make sure we have a list of all registered people at the day of the conference.

This does not include payment, which we have to discuss separately. Once we have a bank account we can technically accept credit card payments, for example through stripe.

Is this you? Then speak up.

**Comment by andrekeller** [comment]
I guess I could do this. Insights of how this was handled last year are of course welcome. Maybe this goes hand in hand with #15 ?

**Comment by href** [comment]
I agree that it does go hand in hand.

Basically we just gathered the information of everyone in a shared spreadsheet, kept tabs on who is who (speaker, helpers, regular attendees), made sure to cross out people who cancelled later and have a printed list in alphabetical order on the day for the registration.

I think at worst it can be a bit tedious to keep tabs on everyone, but I don't recall any special difficulties. Then again, it wasn't my job ;)

I'll send you an e-mail with access information for info@python-summit.ch. The registration form submission don't have to go there, but people tend to enquire later to this address about cancellations and changes - which you should keep track of.

**Comment by chiesax** [comment]
@andrekeller we should now open for registrations.

I did the job last year of polling the sheet from time to time and send confirmations. We decided to do this manually to reduce the overhead to handle an automated system.

Prices:
- regular early bird: 20chf
- businnes early bird: 50chf
- free for SPS members (registration required)

Once we have the account available (estimate at most two weeks) we will send an invoice with payments instructions.

What do you think? Can you set up the google form and the spreadsheet?

**Comment by chiesax** [comment]
Minimal fields on the form: email address, name,  company name, ticket type...

**Comment by dbrgn** [comment]
We should also have a very small section on terms, where we state that users may receive 1 promotional e-mail from our platinum sponsor, sent by us.

**Comment by andrekeller** [comment]
@chiesax I was in holidays the last three weeks and will look into this tomorrow or on Wednesday.

**Comment by andrekeller** [comment]
@chiesax I created a simple form in my own google drive. With whom should I share this ? It would be great if someone could have a quick look over it.

**Comment by chiesax** [comment]
hey thanks yes you can share it with me, my account name is schiesax.

**Comment by chiesax** [comment]
looks good to me.
Should we also add some information about the registration process, something like "you will shortly receive an invoice with payment instructions, registration will be confirmed once the payment has been received" ?

**Comment by andrekeller** [comment]
How about as a message on form submission:

```
Thank you for your registration.

We'll confirm the registration and provide you with an invoice and the payment details in the upcoming days.
```

As @dbrgn proposed in https://github.com/SwissPy/sps17/issues/15#issuecomment-237355015, we can inform them about the reservation conditions in the mail with the payment instructions.

So for the process:
1. they fill out the form
2. I'll send them a reservation confirmation with invoice and payment instructions. Seat is reserved for 30? days
3. @chiesax will mark payed seats in the spreadsheet after money arrived at the bank
4. I'll confirm the registration to the attendants.
5. I'll send a reminder after 30 days to people that we free'd up their seat until payment arrives

How many attendants can we support?

Does this sound reasonable?

**Comment by chiesax** [comment]
as mentioned by @dbrgn in #17, the Aula is suited for 250 attendees.

**Comment by href** [comment]
Are we going to go for all 250, or do we need to reserve some space for booths and the video camera?

**Comment by dbrgn** [comment]
I'd try to limit it to 210-220 for now. We can still allow more people in if there's a waiting list. But we should take a look at the room first.

**Comment by chiesax** [comment]
@andrekeller lets then publish the registration form... I can then add the link to the web site...

**Comment by andrekeller** [comment]
@chiesax that would be great. Also it would help if you can prepare an invoice template, that I can fill out and send to registrants.

**Comment by chiesax** [comment]
OK, but at present the association account is unfortunately not yet ready (there was a mistake in the protocol, so we had to send back some documents) and I would like to add the payment instructions to the invoice. So I suggest that if someone registers, we just send a confirmation, stating that payment instructions will shortly follow...

OR we may wait for the publishing of the registration another week until we have the account...

**Comment by andrekeller** [comment]
Well the problem with allowing registration before we are ready is that it generates unnecessary overhead. So if we can wait until we have the account ready I'd be glad. If you think its necessary to start now, then I'll manage :-)

**Comment by chiesax** [comment]
Then let's wait another week... I'll start to prepare the invoice template, so we can have it ready...

Should we use a plain open office text file, or should we go for a LaTex template?

**Comment by andrekeller** [comment]
both is fine with me... I'll probably fill them in manually anyway...

**Comment by href** [comment]
Can you make sure that we have a company field (for the free sponsor tickets), if you haven't already?

Also we should mention on the registration that we might send a single promotional e-mail from the platinum sponsor through info@python-summit.ch, whilst making clear that we are _not_ sharing anyone's address with said sponsor or anyone else for that matter.

**Comment by chiesax** [comment]
Yes we should add the company field. The promotional terms are already there.

Should we also add a field "number of tickets"? (we just allow to buy many tickets of the same type in one submission)

**Comment by href** [comment]
I wouldn't. We do want a list of individual names at the end. For sponsoring purposes as well as for giving out the tickets. Having N registrations on a single form submission complicates this I think.

**Comment by andrekeller** [comment]
Another thing that came to my mind. Do we need to specify a refund policy? How do we handle cancellations?

**Comment by ccdesales** [comment]
Other conferences offer refunds for requests filled up until specific dates. I'd do the same, let's say somewhere around 3 weeks in advance, when people should have clear understanding if they can make it or not, while allowing ourselves to adapt for things that depend on audience size such as the social event.

**Comment by chiesax** [comment]
@andrekeller the account is finally ready...
Could you add the previous refund policy to the online form? We should also add a statement that we will refund the ticket if the event is canceled by unforeseen circumstances (although I do not even want to imagine the overhead of refunding 200 people :cry: , so we may better not cancel the event... ).

**Comment by andrekeller** [comment]
sorry, I caught the flu an was spending the last 3 days mostly in bed. Will have a look tomorrow the latest so we can get this on the website by the end of the week.

**Comment by chiesax** [comment]
OK, recover well then...

For the invoices we will be using wave:
- I will grant you permissions in wave to send invoices,
- I will create three "products" in wave (regular early bird, company early bird, sps member ticket) and link them to an appropriate "ticket sales account".

To send the invoices the fastest would be to use wave to send the email, but the problem is that **there is no feedback on undelivered mails by wave** (tested it).

We are then left with two options:

A. in wave, choose the option send by Gmail, which will generate a message with the URL to the invoice, we may then copy paste this URL and send it using info@python-summit.ch account, **the advantage of the URL is that, in wave, one can see that the URL has been viewed**
B. in wave, choose the option to generate a PDF of the invoice, and then attach it to the email using info@python-summit.ch account.

I will then check the payments and mark the invoice as paid in wave, and modify the spreadsheet accordingly.

**Comment by ccdesales** [comment]
> we will refund the ticket if the event is canceled by unforeseen circumstances

PyData Cologne 2016 is cancelled because of a fire at their venue!

Get well soon Andre!

**Comment by chiesax** [comment]
if we refund one ticket a day, we will be over in 200 days :grin:

**Comment by chiesax** [comment]
better say, in case of unforeseen circumstances, no refunding of the ticket, but the SPS will donate your money to the Python Foundation :smiley:

**Comment by chiesax** [comment]
... and that's good for your Karma ...

**Comment by dbrgn** [comment]
BY the way, can we change the content of the invoice e-mail? The one I got for the association didn't contain a proper description :)

Attaching a PDF and including a link in a (manual) e-mail would probably look best.

**Comment by chiesax** [comment]
one can add header and footer notes (to the invoice, but the email generated by wave cannot be modified), and a description of the purchased item (footer note contains the the payment instructions), and possibly more

**Comment by The-Compiler** [comment]
> Attaching a PDF and including a link in a (manual) e-mail would probably look best.

I agree. "Below please find a link to Invoice #10." and a random link almost went to spam here :wink:

**Comment by andrekeller** [comment]
Hi @chiesax,

I'm back on my feet :-)

So what do we put as refund policy? I like the donating to PSF idea. Other than that we do not need to adjust anything on the form, yes?

I guess sending the E-Mail using the info@python-summit account and attaching the PDF will work just fine.

**Comment by chiesax** [comment]
OK, let's say then that in case of cancellation of the event the money will be devoluted to PSF...

Then we add the link to your form to the site and let's see how many people are registering...

**Comment by chiesax** [comment]
@andrekeller when you are ready with the form I can modify the site and open the registrations...

**Comment by andrekeller** [comment]
@chiesax: Please proof read my changes a feel free to publish if you are happy with the form.

**Comment by chiesax** [comment]
registration is now open...

**Comment by The-Compiler** [comment]
https://twitter.com/pythonsummit/status/780267813680320513 :wink:

**Comment by href** [comment]
Be aware that the SwissPy repository wasn't updated with the changes pushed to the GitHub. The repository needs a little _push_ ;)

**Comment by href** [comment]
By the way, we should remove 8-10 spots from the amount of people we allow, because until the speakers get their confirmation I would assume they don't register.

**Comment by href** [comment]
I got two questions about this already on info@python-summit.ch:

> I'm considering signing up for the Python Summit 2017 (after I missed the last one because it was sold out when I remembered to check), but the signup form has me stumped. Ticket type options currently read:
> 
> > CHF 20.- for unemployed or self-employed people and/or students (EARLY BIRD)
> > CHF 50.- if a company pays your ticket (EARLY BIRD)
> > SPS membership
> 
> Which type applies to me if I am neither unemployed/self-employed/student nor a company pays > for my ticket?
> 
> I am employed (and occasionally write Python code as part of that employment), but my employer does not pay for my ticket (I assume - I guess I could ask). I am coming as a private individual out of personal interest, not on behalf of my employer.
> 
> Could you edit the form to clarify this?

Can we do that? Maybe add some text to this effect.

**Comment by andrekeller** [comment]
I just posted this on slack as-well:

Is it okay if I add:

```
If you are employed, but you pay for the ticket yourself, you are eligible for a CHF 20.- ticket.
```

**Comment by dbrgn** [comment]
Maybe let's reword instead:

CHF 20.- if you pay your ticket yourself, e.g. unemployed or self-employed people and/or students (EARLY BIRD)
CHF 50.- if a company pays your ticket (EARLY BIRD)

**Comment by chiesax** [comment]
I would also add

CHF 50.- if a company pays your ticked, the company name will be visible on the lanyard cards

**Comment by href** [comment]
> CHF 50.- if a company pays your ticked, the company name will be visible on the lanyard cards

We didn't discuss this yet actually.

**Comment by chiesax** [comment]
Ok, sorry, I was somehow implicitly assuming that businesses tickets will have their company name written on the lanyard cards...

**Comment by andrekeller** [comment]
Hmm good point. I'll add that to the confirmation mail. I'll tell them that the company names are printed on the badges unless they opt out.

**Comment by chiesax** [comment]
@andrekeller please wait, I have moved the discussion to the committee...

**Comment by chiesax** [comment]
We are probably not printing it, since it may be an overhead to handle the printing of the lanyard cards.

**Comment by chiesax** [comment]
Let's have an update on this tomorrow...

**Comment by andrekeller** [comment]
https://www.officeworld.ch/avery-zweckform-namensetiketten-l4784-20-635-x-299-mm-30827.html something like this could be easily printed...

**Comment by href** [comment]
The printing is the easy part. Typesetting 200 names and making sure everyone gets the right tag at registration is the hard(er) part.

But it's certainly doable. Just saying what last year's reason for a single tag was - you need one page, print it n-times and hand it out without doing any lookups. It's as simple as it can get.

Maybe we can do it differently this time around. Last time I was concerned about registration processing times - it didn't help that the idea for the summit was born at Europython 2015 where registration took hours and had many people stand outside while the talks were already going on.

It did work though, we started pretty much on the dot with everyone gone through registration ;)

**Comment by andrekeller** [comment]
Well, I guess it is easier this time, as we do not need to handle payments. I do not think that it takes longer to find a name on a alphabetically ordered list of names than it takes the attendees to fill out their badge.

**Comment by chiesax** [comment]
@andrekeller I like your idea of stickers, it is cheap and we can handle the printing, and are easier to distribute compared to lanyard cards. For a one day event, a sticker may be enough.
Actually we do not really know how many people will pay by bank transfer, and how many on-site, but we could have a set of emtpy stickers to be filled manually for on-site registrations.

**Comment by chiesax** [comment]
Just beware of what written on the sticker box: Nicht geeignet für Wildleder, Samt und Seide 😸

**Comment by chiesax** [comment]
In principle we could even stick the sticker on a lanyard card...

**Comment by chiesax** [comment]
@href could you tell the sponsors that they do not need to register for the tickets they already got? Just adds noise to the registration sheet... Would be great if they could send us a list of participants at some point.

**Comment by chiesax** [comment]
So Seantis has two tickets left...

**Comment by chiesax** [comment]
@andrekeller I have granted you full permissions on Wave. 
I have added the "SPS17 regular early bird ticket" and the "SPS17 business early bird ticket" products, that can be selected when creating an invoice.

**Comment by href** [comment]
I'm afraid I already told them to write the company name and to use a company ticket. If I tell them otherwise now it would seem a bit disorganised from our side, so I'd rather not.

**Comment by andrekeller** [comment]
@href and @chiesax I actually do not mind at all if they sign up. Means we have all attendees in one place.
