### ISSUE TITLE
Deploy an Online Payment Form

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#15]
The best way to ensure that people show up is if they have to pay up front. So as an option we might want to allow for online payments. Once we have a bank account we can for example setup Stripe to go with this.

This does add complexity however, so we can always just go back to last year's pay on premise system.

Thoughts?

**Comment by ccdesales** [comment]
We'll soon have the association's bank account set up. 

People can use the traditional orange sheet to pay (preferably online), and the treasurer can go once a week through the incoming payment list and mark them. Somebody else can then send the confirmation emails.

**Comment by andrekeller** [comment]
I'm not sure we want the overhead and complexity of something like stripe. For attendees from Switzerland/Europe a bank transfer is probably easiest (SEPA/IBAN). We can provide deposit slips on request.

**Comment by dbrgn** [comment]
I agree with @andrekeller. Let's simply use SEPA and red payment sheets (Einzahlungsschein) for pre-payment. Once a reservation is done, it is reserved for 30 days. If there's no payment after that, we'll cancel the reservation.

**Comment by chiesax** [comment]
Sounds reasonable...
