### ISSUE TITLE
Find Sponsors

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#16]
I'm not sure how we should go about this, but we definitely need sponsors. Last year we added the logo to all prints and allowed some sponsors to lay out their material around registration and to give a short presentation.

What should we offer this year?
Who wants to take care of talking to possible sponsors?

**Comment by chiesax** [comment]
We may offer the same package as last year.

I guess the first step would be to contact the last year sponsors and ask them if they want to sponsor us again, letting them know we are now an association, and that they may benefit from tax exemption if they decide to give us some money. Do we have the contacts?

**Comment by chiesax** [comment]
@ccdesales, @href  are Seantis and Webrepublic willing to give the association some money and eventually how much?

**Comment by href** [comment]
Do you mean soon, to get some liquidity, or in time for the conference?

**Comment by chiesax** [comment]
I do not think we need the money right now... but just to have an idea of the amount to make a reasonable budget...

**Comment by href** [comment]
Well to get the same deal as last year, which I guess would be the lowest tier of sponsoring (have the logo on the printed materials and on the website) Seantis would be willing to pay 500.- to 1000.-.

It would make sense to add a higher tier, like the one Beekeeper had last year. I don't know what they payed at the time, but it would have to be a bit more than the lowest tier of course.

So maybe add a second tier for 1500.- to 2500.- that includes a short presentation at the end like last year's as well as a booth.

If we wanted to go all out we could also add a single top-tier sponsor plan which goes for maybe 3000.- to 5000.- which might include a guaranteed speaker spot (it would still have to be something pythonic) and maybe the ability to send a single message through us to all the attendees. That is a mass-email that they can send from our address to everyone that attended. Apparently that's something quite valuable :)

This would mainly be interesting as an anchor point, it would make the second tier look more affordable, because there's a third tier that's more expensive. In the end we might not even need the third tier.

In any case, we would have to limit the spots of those tiers.

We should also have someone pay for the after party. Maybe as part of the third tier, or independently. Anyway, those are the thoughts of my co-workers :)

**Comment by href** [comment]
By the way, it doesn't look like there's a tax credit to be had at this point. I think we would have to become a specific kind of registered association for this to work:

http://www.viavia.ch/verein/pmwiki.php?n=Verein.Steuerbefreiung

But I doubt this is much of an issue anyway, when a company spends more money on things it pays less taxes as the profits are affected. And what really counts is what we offer anyway. So our main argument and focus should be on the conference being an even bigger deal this year with many engineers attending. Those engineers won't stay with their current job forever, so increasing your companies profile with those engineers is easily worth what we're asking.

**Comment by chiesax** [comment]
Ok great news and thanks to Seantis, this will already cover part of the location fees. So if we can get the same from Webrepublic, we have already payed the venue.

**Comment by dbrgn** [comment]
> If we wanted to go all out we could also add a single top-tier sponsor plan which goes for maybe 3000.- to 5000.- which might include a guaranteed speaker spot

I would not agree on "selling" a speaking spot. People pay an entrance fee to see interesting content, not the one that brings us the most money.

Allowing the bigger sponsors to send out a mass e-mail would be OK for me.

**Comment by chiesax** [comment]
Sponsors may also pay for a stand...

**Comment by chiesax** [comment]
I am also somewhat against selling speaking spots, but OK for the rest.

**Comment by chiesax** [comment]
We should also definitely have a 'become a sponsor' section on the web site...

**Comment by ccdesales** [comment]
I'm also in favor of company tickets. 

We could come up with some sponsor packages (free tickets for instance), but I'm not particularly in favor of giving too much power on deciding the conference program.

**Comment by href** [comment]
I'm okay with company tickets, but they need to register anyway, so they don't end up unused.

**Comment by href** [comment]
Without going into pricing yet, this is what I currently have in mind. Let me know what you think.

**Platinum (one spot)**
- Has the logo placed on all promotional materials (large size)
- May send one mass-email to all attendees through us (no sharing of addresses)
- Gets a 5 minute spot at the end of the conference to have a short presentation
- Gets the best booth spot
- Gets five company tickets
- Gets to be sponsor of the afterparty (no additional charge)

**Gold (two spots)**
- Has the logo placed on all promotional materials (medium size)
- Gets the ability to have a booth spot
- Gets three company tickets

**Silver (three spots)**
- Has the logo placed on all promotional materials (small size)

[Edit]
The number of six sponsors is mainly chosen because more than that is going to be hard to fit onto posters and stuff. I also added the afterparty info to Platinum.

**Comment by href** [comment]
I'm however still unclear on how to add the t-shirt / lanyard sponsoring of last year into these tiers.

**Comment by ccdesales** [comment]
> I'm however still unclear on how to add the t-shirt / lanyard sponsoring of last year into these tiers.

I see not need for it. Sponsors will give us money and we buy what we need with that.

**Comment by href** [comment]
I don't mean that they need to pay for it. I mean if you are the platinum sponsor, you might want to have your logo on the shirt. Or maybe the gold sponsors should have theirs on it as well.

**Comment by ccdesales** [comment]
I see. We could offer them to provide us the lanyards, as some are quite
picky with their image copyrights.

**Comment by dbrgn** [comment]
If there are no logos on the shirts we might even reuse them a year later :)

The platinum sponsorship should probably also include this line:

> Has the logo placed on all promotional materials (large size)

**Comment by href** [comment]
As per last nights committee meeting, these are the agreed upon sponsorship plans. They will also be detailed in the meeting protocol which will go out to all members later today:

**Platinum Sponsor (2000 CHF)**
Only one spot available!
- Has the logo placed on all promotional materials in the largest size (relative to other sponsors).
- May send one mass-email to all attendees through us (no sharing of addresses).
- Gets a five minute spot at the end of the conference, before closing remarks, to have a short presentation.
- Gets a boot spot and first pick as to which one.
- Gets five company tickets.
- Is named official sponsor of the afterparty.

**Gold Sponsor (1000 CHF)**
Two spots available.
- Has the logo placed on all promotional materials in medium size (relative to other sponsors).
- Gets a booth spot.
- Gets three company tickets.

**Silver Sponsor (500 CHF)**
Three spots available.
- Has the logo placed on all promotional materials in small size (relative to other sponsors).

**Comment by href** [comment]
The plan is also available on the website now: http://www.python-summit.ch/pages/call-for-helpers.html#help-us-by-sponsoring-our-event

One gold spot is already gone.

**Comment by ccdesales** [comment]
I've written Beekeeper and Divio to check whether they'd be interested in taking one sponsor spot.

**Comment by href** [comment]
With the last open sponsoring spot potentially filling up these days we can close this.
