### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/sps17#17]
Blocks #9.

What expenses can we expect?

If we can't get the room for free (it would probably be easier not having to target a break-even):
- Location rent (including cleaning and other expenses)
- Technical equipment (sound, adapters, etc)
- Printing costs for flyers, posters, etc
- Coffee and food during breaks
- Social event (if we decide to do one)
  - Beer
  - Catering
- Name badges / Lanyards
- Staff shirts
- Drinks for speakers and helpers
- Maybe free entry for speakers and helpers
- Maybe travel expenses for speakers
- Varia

**Comment by dbrgn** [comment]
How many people should we allow? I think we could do our budget based on 200 and allow up to around 250. That should be possible in the Aula.

**Comment by chiesax** [comment]
I am not sure you already did this, but could we provide a more or less detailed list of last year expenses, this would give us a more quantitative idea...

**Comment by chiesax** [comment]
@sfkeller could you give us an estimate for the location rent?

**Comment by sfkeller** [comment]
Aula (incl. Aula Foyer e.g. for Apéro) 600.-; plus 120.- "Hauswart/Bühnenmeister"; plus Beamer 150.-. 
More Aula Office infrastructure (Micro)? => plus 250.-.
I hope I did not forge s'thing: More rooms?

**Comment by chiesax** [comment]
Reported from last year budget...

Covered

 costs

```
Venue (sponsored by HSR)
Catering (we're doing our own)
Social event excluding beer (sponsored by Beekeeper)
Shirts and Lanyards (sponsored by Divio)
Lanyard card sleeves (sponsered by Seantis)
Microphones (@dbrgn could borrow some for free)
Website (Github)
Helpers / Speakers (no reimbursements)
```

Open costs

```
Coffee / Snacks: ~900 CHF (about 120 * 7.50 CHF according to @sfkeller)
Two Cash boxes: 44 CHF
Beer: 200 CHF (160 bottles * 1.28 CHF, free delivery)
Thick paper for lanyard cards: 10 CHF
Water for speakers: 10 CHF
```

Unsure

```
Cleaning staff: could there be additional costs for cleaning, @sfkeller?
Lanyard card printing: could we print them at HSR, @sfkeller?
```

Income

```
Entrance fees: 1100 CHF (110 * 10, speakers and HSR students don't need to pay)
```

Result

With the current data: 1164 CHF - 1100 CHF = -64 CHF

**Comment by chiesax** [comment]
What about HSR students tickets prices? Do they get free/reduced fee entry even if we pay the room?

**Comment by chiesax** [comment]
@sfkeller In case we are paying the room, do you think we need some sort of insurance?

**Comment by sfkeller** [comment]
There exists already an insurance at the university.
Regarding HSR students tickets: I'd suggest to give discount to all students (at least HSR); that was a suggestion by our financial officer. How much this discount is, can you (the organizing committee) decide.

**Comment by dbrgn** [comment]
We could adjust student prices (for all universities) so that they only cover the food costs, but don't account for room and material costs. 50% could work. What do you think? We should have enough room.

Could we also offer company tickets? For a company, 50-100 CHF is peanuts. But it would allow us to give out regular and student tickets even cheaper. See #9.

**Comment by jakeret** [comment]
Having different prices makes the registration process and setting up the budget harder. At least last year we tried to keep everything simple and stupid

**Comment by dbrgn** [comment]
What about this (without having calculated it through):
- Student 10 CHF
- Regular 20 CHF
- Company 50 CHF

All of this for pre-order. On-site: +10 CHF.

We'd have to calculate how much money we'd get from that in worst-case and best-case scenarios. And then see how much is missing.

**Comment by ccdesales** [comment]
Don't forget that for company tickets we need to have actual invoices, as they're used for tax purposes.

**Comment by dbrgn** [comment]
Would that be hard to do? I have a LaTeX template that we could adjust if someone requests it. Don't think we would need to provide invoices by default.

**Comment by chiesax** [comment]
How do we handle early bird tickets?

**Comment by chiesax** [comment]
Should we increase the price if people pay on-site, or just open for on-site payments later (like one month before the conf), or both?

**Comment by dbrgn** [comment]
What about allowing pre-payments until 2 weeks before the event with the reduced price, and then only allowing on-site payments? This way all pre-payments will be processed in time.

**Comment by chiesax** [comment]
Meaning that reservations for on-site payments open 2 weeks before the event, with the same mechanism as last year?

**Comment by dbrgn** [comment]
That is my suggestion, yes. What do you think? This will also reduce the number of people that sign up and don't come to the event.

**Comment by chiesax** [comment]
Sounds good to me...

**Comment by chiesax** [comment]
... hopefully people will prefer to spend some time to make pay us online, rather than speculating they can still get ticket on-site...

**Comment by chiesax** [comment]
What I mean is that we could also consider an extra charge for paying on-site (like 5 CHF).

**Comment by dbrgn** [comment]
Yes, that's what I suggested in my (edited) comment above :) 10 CHF would be a benefit in that we don't need that many coins but can use paper money instead. But 5 CHF would be OK too (although it's not much of an incentive to pre-pay anymore.)

We could also offer payment via bitcoin through https://bitpay.com/, it's really simple to set up. They send the transferred money in fiat currency to a SEPA bank account. But @chiesax would have to decide whether he wants to support something like that.

**Comment by chiesax** [comment]
10 CHF is even better, will give a stronger motivation to pre-pay.
As for bitconins, lets have it as a nice-to-have feature. Lets see how fast Postfinance is setting up our account before...

**Comment by dbrgn** [comment]
Cool!

Bitpay free account offers up to 30 transactions per month and up to 1000$ daily. I think that should be enough for us. Business would cost 1% transaction fee (still much lower than credit cards around 2-3%).
