### ISSUE TITLE
Keep Track Of and Manage Helpers

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#18]
We need someone to keep track of all the helpers that want to help on the day of the conference and who is in charge of assigning them to various jobs.

This includes being on top of the helpers on the day of the conference. Making sure they know what to do and where to go.

Helpers are currently registered through the e-mail address. So anyone doing this job should be monitoring the incoming e-mails. See http://www.python-summit.ch/pages/call-for-helpers.html

Helpers that want to join the association are of course handled by me. This is only about the helpers that do not join the association.

A first step would also be to contact the helpers of last year, which haven't joined the association. @ccdesales do we still have the list of those people?

Speak up if you want to do this! It's almost like you become the king of a band of misfits ;)

**Comment by ccdesales** [comment]
There are a couple of people who have registered as helpers and who are not part of the association. You can find the spreadsheet with their names by searching your Google Drive for "Registration for Collaborators 2017 (Responses)". Please ping me if you need access.

**Comment by href** [comment]
As long as nobody's taking over this task I'll do it. Since I'm limited on time I'd appreciate help though. I mainly don't know how to attract more helpers at this point. Maybe we should eventually ask all the attendees to signup to a helpers list separately.

Until then I'll keep track on the already existing helpers sheet:
https://docs.google.com/spreadsheets/d/1h7zmFT1L33Wx5BAnzAepZIHGUo3yUJASSVhhPKPRa54/edit#gid=694625947

Please add any people that we can count on to the sheet, should you get contacted directly. Be sure to note what they can do. As we assign more people we'll go from what they *can* do to what they *will* do.

Also all association members which are going to be present should add themselves (and possibly the thing they'd like to do on-site).

@sfkeller Can you add your interns to the list as well?

**Comment by sfkeller** [comment]
> @sfkeller Can you add your interns to the list as well?

Done.

**Comment by href** [comment]
Since we'll also need t-shirts for all helpers, I've added a t-shirt size column. Please add your shirt-size to the list and if you haven't already, add yourselves to the list of helpers. You want to be on this list to get a t-shirt ;)

See also https://github.com/SwissPy/sps17/issues/12 where the t-shirt will be defined.

**Comment by bkarolina** [comment]
How many helpers have you got last year? Or, how many helpers do you think it will be needed?

**Comment by href** [comment]
That's a good question. I think including interns and ourselves we were like 10 people? Does anyone have reliable data?

**Comment by dbrgn** [comment]
I can share last year's helper spreadsheet with you, @href!

**Comment by href** [comment]
Thanks! We had 15 helpers last time. I think that's a good number to aim for again this time around.
