### ISSUE TITLE
Define location for SPS17

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/sps17#2]

**Comment by dbrgn** [comment]
Rapperswil would probably be available again, and we could probably get the Aula, which is bigger.

**Comment by ccdesales** [comment]
I've written a mail to Martin Christen from the FHNW, asking him about the option of hosting the event in Olten. As a central location it could boost attendance.

> Dear Martin,
> 
> ```
> This is César Cardenas from the Swiss Python Summit 2016 organising team. 
> 
> I'm reaching out to you because we are organising the next version of the event. In special we are considering options for the venue. I recall you work for the FHNW, and since it's known they have a campus in Olten (an ideal location for a nation wide conference) I was wondering whether you would be willing and able to provide some input regarding the possibility of hosting our event there.
> 
> As you know the Python Summit is a community oriented non-profit conference, and because of that we try to kept the costs close to zero, but maybe this may be beneficial for the University to promote their Computer Science program.
> 
> Thanks for your response.
> 
> Best regards,
> César
> ```

**Comment by ccdesales** [comment]
Martin has indicated that while it's relatively easy to get the venue in Olten, he's not available as our contact person on February 2017. It was also discussed that in both cases, Olten and Rapperswil, the event needs to take place during the semester break, so we are constraint to have it on February or in Summer.

This means we are most likely returning to HSR Rapperswil on February 2017.

**Comment by ccdesales** [comment]
@sfkeller would you please check which would be the best dates if we wanted to host the conference in 2017 at HSR?

**Comment by sfkeller** [comment]
Ok. I'll do that. 
As a quick answer it must be before semester starts which is 20.02.2017.
If needs to be a Friday again, it's February 3/10/17 2017. 
Does it need to be a Friday?

**Comment by cdesales** [comment]
I think it makes sense that it's on Friday, for same reasons as last year.

**Comment by dbrgn** [comment]
I think 17.3. is probably the best date - by then all exams should be finished.

**Comment by sfkeller** [comment]
Then I have called the "Verwaltungsdirektor" himself since, yes, 17. February 2017 could be an option - but we have a problem: The Aula is still reserved for exams and will be renovated until August 2017 (which means there could be too much noise)! I/we now have to investigate if 17. February 2017 can be made available.
Thus, I have reserved as a fallback >> Room 3.008 << (max. 130 persons) on Friday 10. and/or 24. February 2017 (this room is not available at 17. February 2017).

**Comment by dbrgn** [comment]
We planned to do a bigger edition this time, so we'd probably need room for at least 200 people.

Is there any chance we could get the aula?

**Comment by sfkeller** [comment]
I'm investigating (with help from Frau Vettiger), if 17. February 2017 can be made available. Chances are 50/50. I'll update you tomorrow.

**Comment by dbrgn** [comment]
Other dates might also be possible from our side.

Furthermore, depending on how much the fee would be, we might also be able to pay regular fees for the room.

**Comment by sfkeller** [comment]
It seems that the Aula would be available at Fr. 10. Feb. and/or Fr. 17. Feb. 2017. Which date do you prefer?

**Comment by href** [comment]
I don't see any conflicts with other conferences on lanyrd.com, I don't know what else we could check.

One thing that the 17th has going for it is that it's almost symmetrical: 17.02.2017, so it's easier to remember :)

**Comment by sfkeller** [comment]
So, without any other feedback, I will confirm internally tomorrow around lunch time that we take the date Fr. 17.02.2017 for the Aula HSR.

**Comment by dbrgn** [comment]
That would be great!

What would the regular prices for the Aula be, just in case we want to go all-in on sponsors and financing?

**Comment by sfkeller** [comment]
Unconfirmed prizes: 
The Aula (main lecture hall, Auditorium Maximum) is around CHF 660.- (whole day incl. one hour technician). 
Don't know if this includes the beamer which would cost 150.- on top. 
Then we'd need a Foyer for reception and apéro which would be CHF 150.- (my guess). 
Lecture rooms 3.008 and 3.010 are CHF 250.- each for whole day.

**Comment by sfkeller** [comment]
The date is set: It's the Fr. 17.02.2017 in the Aula.
The full costs (in CHF) are as follows:
- 600.- Aula including Foyer (for reception, breaks and Apéro)
- 120.- Operator ("Bühnenmeister")
- 150.- Beamer
  That's it for the room and infrastructure. There's no need for a separate "Cafeteria" room since the Foyer is just close to the Aula. During breaks the doors between Foyer and Aula need to be opened to give space.
