### ISSUE TITLE
Social Media Communication

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#20]
Now this one is fun. We need someone to man our Twitter account before and most importantly during the conference. As an added bonus you can call yourself a social media expert after a few tweets! ;)

Anyone interested, speak up.

You are also welcome to delegate this to a day-of-the-conference helper, if you can find someone. Last year I think we had an attendee that did it.

**Comment by The-Compiler** [comment]
Sounds like fun indeed - this is something I could see myself doing :smile:

**Comment by href** [comment]
The job is yours! :)

[This is you, right?](https://keybase.io/the_compiler) - If so, I'll send the credentials to this contact.

Happy tweeting!

**Comment by href** [comment]
Silly me, I can actually verify it's you :)

**Comment by dbrgn** [comment]
If you need assistance, https://twitter.com/birdy1976 did a great job last time :)

**Comment by The-Compiler** [comment]
I think we can set up [Tweetdeck](https://tweetdeck.twitter.com/) so various people can be given permission to tweet with that account easily - at least that's what we did for [`@pytestdotorg`](https://twitter.com/pytestdotorg). Then I'd propose adding birdy1976 and anyone else here who feels like they have something good to say to that.

Does that sound like a good idea?

**Comment by The-Compiler** [comment]
I did set up tweetdeck now and it works beautifully - if anyone else wants access to the account, let me know!

**Comment by href** [comment]
@The-Compiler Sign me up! I could use it for some timed tweets about our sponsors :)

**Comment by href** [comment]
We should increase our tweeting before the conference, to maybe get some extra attendees and make sure that people are well informed. Anyone want to help out? I'm a bit preoccupied with other things :)

**Comment by dbrgn** [comment]
Maybe @The-Compiler?

**Comment by The-Compiler** [comment]
Busy with exams currently, so probably rather not :wink:

**Comment by ccdesales** [comment]
I'm doing this for the time being.
