### ISSUE TITLE
Manage the Website

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#21]
We need a website manager that updates the content on the website. Since this is handled [in a repository](https://github.com/SwissPy/SwissPy.github.io) we of course can all work on it.

But as the responsible person you would be in charge of the design, the site structure and you'd be making sure that the end-result always looks great and stays up to date.

Of all the jobs we got, this is probably the most dev-like. So if you have some rudimentary website chops, you can basically do everything you need to do from the command line.

Speak up if this is you ;)

**Comment by chiesax** [comment]
We should now open for registrations, the form by @andrekeller is ready to go online...

Also, do not forget to add sponsoring informations, and some words about the association.

We urgently need someone to manage the website!!!

**Comment by href** [comment]
> Also, do not forget to add sponsoring informations, and some words about the association.

We already got that ;)
http://www.python-summit.ch/pages/call-for-helpers.html

As for the registration, you should be able to push your own changes. As long as we have no-one specifically responsible for the website each team should probably just do the changes they way they see fit.
