### ISSUE TITLE
Show a Picture of the new Room on the Website

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#23]
We should add a picture of the room on the website. This will make it clear that we are doing it a bit bigger this time around. It would also be useful for the sponsors.

@dbrgn Can you post the picture you shared in the chat at our last committee meeting?

**Comment by dbrgn** [comment]
Here are some pics. The room:

https://www.iwk.hsr.ch/uploads/pics/20130905_RAKUFO8_pic1.jpg

Size of the stage:

http://www.linth24.ch/uploads/pics/Diplomfeier_HSR_Sept_2014.jpg

They're not particularly good though, and I'm not sure if we can use the pictures. Maybe I can drop by and take a few pictures.

**Comment by href** [comment]
> They're not particularly good though, and I'm not sure if we can use the pictures. Maybe I can drop by and take a few pictures.

Please do if you have a chance 👍

**Comment by href** [comment]
I'm not sure we need this anymore.

**Comment by dbrgn** [comment]
I still think it would be good to have for the speakers.

**Comment by dbrgn** [comment]
![img_8104](https://cloud.githubusercontent.com/assets/105168/21722470/1400b114-d42d-11e6-86ff-ad0605d1748a.jpg)

![img_8106](https://cloud.githubusercontent.com/assets/105168/21722472/175f40aa-d42d-11e6-8441-6f41ca1d520a.jpg)

**Comment by dbrgn** [comment]
I added it to the "venue" page. Please reopen if you think it should also be on the home page.
