### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by The-Compiler** [SwissPy/sps17#24]
Do we want SPS17 stickers?

I ordered stickers before at [Flyeralarm](http://www.flyeralarm.com/ch/shop/configurator/index/id/34/aufkleber-outdoor.html#) and was really satisfied with them - and they're really cheap!

For example, for DIN A8 Stickers (5.2 x 7.4cm) 1000 stickers would be 33 CHF (100 are 26 CHF :wink:).

If someone can take care of a design, I can take care of ordering them and getting them to the conference.

**Comment by href** [comment]
I'm okay with this :)

**Comment by jakeret** [comment]
Cool idea

**Comment by The-Compiler** [comment]
As for the design, what about just filling up [python-summit-with-text.svg](https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/python-summit-with-text.svg) at the top/bottom so it fits on an A8 sticker, with a little margin at the left/right?

Can I order them and then get the money reimbursed somehow? How many?

**Comment by href** [comment]
Why not just use the logo without text? Ideally cut around the edges?
Or were you thinking of having rectangle stickers?

As for ordering, I'd wait until we get the sponsoring money. Also, the treasurer should have the last say on this :)

**Comment by The-Compiler** [comment]
Logo only with a square sticker (4x4 or 5x5cm I'd say) would work as well, sure!

**Comment by href** [comment]
In this case I'd vote for circle stickers.

**Comment by chiesax** [comment]
I agree lets wait at least for signed sponsor contracts and membership fees. 33chf should not be a problem, I can then refund you by bank transfer...

**Comment by dbrgn** [comment]
I'd also vote for circle stickers with the logo only, if that's available :)

**Comment by chiesax** [comment]
We have 80CHF on the account, I would wait for the first sponsor payment for the stickers...

**Comment by href** [comment]
@The-Compiler You got the stickers already, right? If so, please close this tickets (and do bring them to any future meeting ;)

**Comment by The-Compiler** [comment]
No, I didn't order anything yet. I guess I could now?

It'd be great if someone else could take care of doing a design though, my Inkscape just crashes... :cry: 

Probbably just the SPS logo in a circle (which is not part of the SVG), with 4cm diameter (smaller/bigger ones would als be available, but I think 4cm is about right).

See the [datasheet](https://www.flyeralarm.com/sheets/de/aufkl_mini_rund_4,0.pdf) for details.

**Comment by chiesax** [comment]
Yes we can order them, just keep the receipt and I'll refund...

**Comment by The-Compiler** [comment]
I'll order as soon as someone can give me a graphic conforming to the datasheet then (PDF or TIF, 300dpi, also [see this](https://www.flyeralarm.com/ch/content/index/open/id/20010/druckdaten.html#DatenAusBildbearbeitungsprogrammen)). Can't really easily do that with a broken Inkscape...

**Comment by dbrgn** [comment]
I'll give it a try.

**Comment by dbrgn** [comment]
Something like this?

![rect4585](https://cloud.githubusercontent.com/assets/105168/20810525/5ab588d0-b80a-11e6-9751-d911f25a4dcc.png)

Or do you want the name on it too?

**Comment by dbrgn** [comment]
Here's a version with text and border:

![rectv2](https://cloud.githubusercontent.com/assets/105168/20811686/f6647904-b80e-11e6-9758-966f316d41d0.png)

**Comment by dbrgn** [comment]
@The-Compiler it looks like they want CMYK. Did you order with them in the past? Was RGB fine too? Inkscape doesn't support CMYK natively.

**Comment by The-Compiler** [comment]
I *think* RGB would be fine. Last time I used scribus to assign CMYK colors and tested them on a normal printer FWIW. I can do that part though, Scribus seems to work fine here :wink:

FWIW I prefer the KISS version without text, just looks more clean/simple/professional to me. What do others think?

**Comment by chiesax** [comment]
Yes I also prefer the version without text, I don't like the fonts and their size, and there is too much text.

**Comment by chiesax** [comment]
Maybe just have these words: Swiss Python Summit Association: And each word at 45deg from the other, as to form a swiss cross:

   

> 
          'python' 
Swiss    SNAKE   Summit
              Association

**Comment by chiesax** [comment]
![spssticker2](https://cloud.githubusercontent.com/assets/4541764/20824863/380986dc-b860-11e6-8483-0351de47e730.png)

**Comment by chiesax** [comment]
... I do not have time now to make curved text, just to give an idea...

**Comment by chiesax** [comment]
![spssticker3](https://cloud.githubusercontent.com/assets/4541764/20825161/94137346-b862-11e6-942e-6ab95b231169.png)

**Comment by chiesax** [comment]
Maybe we can remove association?

**Comment by The-Compiler** [comment]
I agree with that, but I think I still would prefer the one without any text.

**Comment by dbrgn** [comment]
I'd prefer the version with the name and URL, but the plain version would be fine for me too.

>  don't like the fonts

It's the one we use on all our print materials.

> there is too much text

What if we only leave the URL and remove the name?

**Comment by jakeret** [comment]
The one without the text looks really nice but somehow it might not be directly clear what's being represented. 
I also like the one with the URL - makes it much clearer. Maybe color the text?

**Comment by dbrgn** [comment]
This would be the one with URL only:

![rectv2](https://cloud.githubusercontent.com/assets/105168/20826269/01d8fe8a-b86a-11e6-8dcd-7a06f4e4c714.png)

**Comment by chiesax** [comment]
can you try this but with the dark blue color of the pyramid, or the dark yellow color of the pyramid? Looks more harmonic to me if we use the same colors as the logo.

**Comment by dbrgn** [comment]
![rectv3](https://cloud.githubusercontent.com/assets/105168/20826334/6feb24b6-b86a-11e6-8497-50b965a32059.png)

![rectv4](https://cloud.githubusercontent.com/assets/105168/20826364/9bb35d52-b86a-11e6-92db-69a6d56e727e.png)

**Comment by chiesax** [comment]
I like it more, but it's somehow asymmetric. Maybe we can keep the "Swiss Python Summit" on top, with the same color?

**Comment by dbrgn** [comment]
![rectv7](https://cloud.githubusercontent.com/assets/105168/20826494/9c9956b2-b86b-11e6-9f1a-62dad5495e93.png)

**Comment by dbrgn** [comment]
And here's a version with slightly smaller logo (the current one looks a bit "crowded"):

![rectv8](https://cloud.githubusercontent.com/assets/105168/20826519/cb019712-b86b-11e6-852f-d3cd5da1926f.png)

**Comment by chiesax** [comment]
which fonts are you using, I want to try another one just for fun

**Comment by chiesax** [comment]
... anyhow this last one is a good candidate to me...

**Comment by dbrgn** [comment]
It's Open Sans.

Here's the SVG for further experimentation: 

[python-summit-sticker.svg.zip](https://github.com/SwissPy/sps17/files/626587/python-summit-sticker.svg.zip)

**Comment by chiesax** [comment]
thx

**Comment by The-Compiler** [comment]
I'm not sure if we can do the border - they show a "Sicherheitsabstand" of 4mm there. Either we can't print anything in those 4mm, or we should probably print the border bigger (over the "cut" of the sticker) to make sure there are no white spots. Not sure...

**Comment by chiesax** [comment]
![python-summit-sticker](https://cloud.githubusercontent.com/assets/4541764/20826939/c735595e-b86e-11e6-9125-49c9da0b16bb.png)

**Comment by chiesax** [comment]
Don't have Open Sans, so I used Sans. Just to give an idea. This way we do not have the border problem.

**Comment by The-Compiler** [comment]
That URL is wrong - the correct one is a bit longer, and I think to look good it needs a bit more space around it. But then it'll probably be too small.

**Comment by dbrgn** [comment]
That'll probably be too small if the diameter of the entire sticker is 4cm.

**Comment by chiesax** [comment]
true

**Comment by chiesax** [comment]
![python-summit-sticker2](https://cloud.githubusercontent.com/assets/4541764/20827158/5da054c4-b870-11e6-967a-553637ee1914.png)

**Comment by chiesax** [comment]
![python-summit-sticker3](https://cloud.githubusercontent.com/assets/4541764/20827205/b0804bae-b870-11e6-90fc-f12043a2c4df.png)

**Comment by chiesax** [comment]
... not easy ...

**Comment by The-Compiler** [comment]
FWIW @href, @dbrgn and I earlier agreed on having the logo without any text :wink:

It's still what I prefer, followed by my initial suggestion (having [python-summit-with-text.svg](https://github.com/SwissPy/SwissPy.github.io/blob/source/content/images/python-summit-with-text.svg) on a rectangular A8 one).

I don't think we'll get the text to look good on a round sticker with a big logo.

**Comment by chiesax** [comment]
![python-summit-sticker4](https://cloud.githubusercontent.com/assets/4541764/20827380/e251a190-b871-11e6-87c6-784b26545197.png)

**Comment by chiesax** [comment]
swiss compromise
![python-summit-sticker5](https://cloud.githubusercontent.com/assets/4541764/20827497/9c8b1dde-b872-11e6-85ff-af3838fa9955.png)

**Comment by chiesax** [comment]
![python-summit-sticker6](https://cloud.githubusercontent.com/assets/4541764/20827537/103e357c-b873-11e6-9136-ce99203c6cc3.png)

**Comment by chiesax** [comment]
what about this last one?

**Comment by The-Compiler** [comment]
I find that text confusing. It's not the "swiss summit" :wink:

**Comment by chiesax** [comment]
anyhow python is implicit (there is already the python logo)

**Comment by dbrgn** [comment]
People won't get that :)

I see two ways in which the sticker could be used:

Without text:

- People see it, find it cool and ask what it's about
- People see it and already know it
- People see it but have no idea what it represents

With URL on it:

- People see it, don't yet know the summit but understand what it is based on the text
- People see it, don't yet know the summit but can visit the URL if they're interested

I don't see any added value in a text like "Swiss Summit" :) And again, try to scale the image to match 4cm diameter on your screen and then try to read the text again.

> FWIW @href, @dbrgn and I earlier agreed on having the logo without any text :wink:

No, I still prefer the version with the text on it: https://github.com/SwissPy/sps17/issues/24#issuecomment-264393803 But would be OK with a no-text version. And @jakeret also mentioned that he prefers text :)

Compromise - how expensive is it to order both versions?

**Comment by The-Compiler** [comment]
@dbrgn I was referring to https://github.com/SwissPy/sps17/issues/24#issuecomment-248823377 :wink:

Prices for the 4cm round ones:

100 Stk.	CHF 38.62
250 Stk.	CHF 40.32
500 Stk.	CHF 46.92
1000 Stk.	CHF 49.31
2500 Stk.	CHF 65.50
5000 Stk.	CHF 94.64

double that if we want two designs.

**Comment by dbrgn** [comment]
> @dbrgn I was referring to https://github.com/SwissPy/sps17/issues/24#issuecomment-248823377 :wink:

Got me :laughing: That was before I tried the different versions though :)

**Comment by The-Compiler** [comment]
FWIW I find https://github.com/SwissPy/sps17/issues/24#issuecomment-264393803 okay too. Wonder how it'd look without the border (and maybe scaled up a little bit) though.

**Comment by chiesax** [comment]
![python-summit-sticker7](https://cloud.githubusercontent.com/assets/4541764/20827978/834f2100-b875-11e6-9419-8ca070e59a37.png)

**Comment by chiesax** [comment]
... yes on 4cm diameter it is not so visible...

**Comment by chiesax** [comment]
... but I am still convinced there must be an esthetically satisfying solution to put the text inside the logo...

**Comment by chiesax** [comment]
(just I don not have more time for trials :unamused: )

**Comment by dbrgn** [comment]
> Wonder how it'd look without the border (and maybe scaled up a little bit) though.

![rectv8](https://cloud.githubusercontent.com/assets/105168/20828250/efb2d4d0-b876-11e6-9775-481f7d47999a.png)

The curvature isn't correct, I could still fix that if desired.

> ... but I am still convinced there must be an esthetically satisfying solution to put the text inside the logo...

I like the approach but don't think it's going to work out on this scale.

**Comment by chiesax** [comment]
This one is good to me!

**Comment by The-Compiler** [comment]
I think that with the correct curvature would be fine

**Comment by dbrgn** [comment]
Like this?

![rc1](https://cloud.githubusercontent.com/assets/105168/20828577/7eb4370e-b878-11e6-94b0-5052e1c7e2b7.png)

**Comment by chiesax** [comment]
:+1:

**Comment by chiesax** [comment]
It's an impression or the text curvature circle is visible?

**Comment by dbrgn** [comment]
Yeah, initially that was still slightly visible. I fixed it and re-uploaded the image, but Github caching seems to keep the old version... In the final version that'd be gone :)

**Comment by The-Compiler** [comment]
Does this have 4mm space outside of the text?

**Comment by chiesax** [comment]
As for the ordering budget, I'd say we can could go for the 1000 stickers. There is only 10CHF difference between 100 and 1000. And 1000 are enough for this year.

**Comment by The-Compiler** [comment]
Yeah, it's crazy how stickers scale :wink: If we don't use them all this year, we can always keep them for the years to come as long as we have the same name and logo.

**Comment by dbrgn** [comment]
> Does this have 4mm space outside of the text?

![rc2](https://cloud.githubusercontent.com/assets/105168/20829890/6124a628-b87e-11e6-9772-4db71aa618d6.png)

Now it does. OK?

**Comment by chiesax** [comment]
:+1:

**Comment by chiesax** [comment]
Actually, this version of the sticker is really cool!
We could also imagine to print the same sticker in 4cm plus a bigger size, like 5cm?

**Comment by jakeret** [comment]
![37162448](https://cloud.githubusercontent.com/assets/11830719/20843672/89103920-b8bc-11e6-9f64-3d92614ef187.jpg)

**Comment by jakeret** [comment]
The last one is really nice. Is it the same font as the one on our website? How about bold?

**Comment by dbrgn** [comment]
Yes, it's Open Sans.

Here's a PDF (version 1.3):

[python-summit-sticker-noborder.pdf](https://github.com/SwissPy/sps17/files/629007/python-summit-sticker-noborder.pdf)
[python-summit-sticker-noborder-white.pdf](https://github.com/SwissPy/sps17/files/629008/python-summit-sticker-noborder-white.pdf)

The first version still contains the grey background to see the actual shape of the sticker. It's 54x54mm with the circle being 40mm in diameter.

@The-Compiler is it OK like this? I'm not sure about color space etc.

**Comment by The-Compiler** [comment]
LGTM from a (very) quick look, their data check will probably tell me more once I place the order.

I also would like to opt-in for the "better" data check for 5.50CHF, which detects more mistakes and lets me take a look at the results before letting them print them (with the basic free one, if the data is readable it gets printed essentially).

That'd be a total of CHF 55.25 including VAT - I'll wait for a final ACK from @chiesax and order then :wink:

**Comment by chiesax** [comment]
👍

**Comment by The-Compiler** [comment]
So I see two issues (but the data check succeeds :laughing:)

- The text is inside the "Sicherheitsabstand", which means it might get cut off (I think). Then again, it's a 4mm margin and we are around 2mm into it, so I hope that'll be alright...
- For some reason, their upload detects a second blank page (even if I convert it to a tiff) and I can't see why... and their preview with the cuttings just shows the cuttings, so I think if we'd order like this we'd get a sheet of blank stickers :laughing: 

I might just pass by at their shop in Zurich somewhen this week if nobody has an idea what could be wrong...

**Comment by dbrgn** [comment]
> The text is inside the "Sicherheitsabstand", which means it might get cut off (I think). Then again, it's a 4mm margin and we are around 2mm into it, so I hope that'll be alright...

Oh. Well, I did add a smaller circle representing the "Sicherheitsabstand", but I probably subtracted 4mm from the diameter, not from the radius... I also think that this should be enough (but I could try to add even more spacing).

Regarding the extra page, even when I import the PDF in Gimp it only shows a single page...

**Comment by chiesax** [comment]
I have seen they also print stickers with 5cm diameter. It is just slightly bigger, but may be more appropriate to fit the text and the logo.

**Comment by The-Compiler** [comment]
I have already ordered the 4cm ones (you upload the data after ordering), I'd rather not try to cancel that again now...

**Comment by chiesax** [comment]
OK lets see how it goes. Just consider this option if you pass at their shop and are discussing with them.

**Comment by chiesax** [comment]
by the way can you not just call them by phone?

**Comment by The-Compiler** [comment]
I probably could, but getting some help in-person seems easier :wink:

**Comment by The-Compiler** [comment]
So I did end up calling them, and that's apparently some bug with their web interface.

However, they noticed the sticker isn't centered properly:

![centered](https://cloud.githubusercontent.com/assets/625793/20965130/a9bc98ba-bc74-11e6-902e-26598563ef76.png)

Us going over the blue line a bit shouldn't be a too big problem they said (they've seen worse :laughing:)

If you look at the distance from the text to the white line, it's off-center for ~1mm already, and with some ~1mm tolerance that'd probably look quite bad.

@dbrgn can you fix that?

**Comment by Feuermurmel** [comment]
A side note about the 4mm safety margin: That margin is just there to keep people from placing important stuff too near to the border and has no impact on printing.

One thing we have to keep in mind is that when cutting the sticker, there's going to be a certain variance in positioning (probably well below 0.5mm). Now with a symmetric design that is very close to the border, a small shift to one side could make that distance between design and border suddenly seem very asymmetric. 4mm is very generous but I'd recommend to keep the text 2.5 to 3mm from the border.

@The-Compiler Do you think we will have those stickers ready to take some to the Chaos Communication Congress? Would be awesome!

**Comment by The-Compiler** [comment]
Can't really tell, but I'll order as soon as everything seems alright and then they'll need 1-2 weeks.

**Comment by dbrgn** [comment]
Better?

![rc2](https://cloud.githubusercontent.com/assets/105168/21008144/af8cb4ce-bd40-11e6-80ef-181bcd88e9a7.png)

And here's the PDF

[python-summit-sticker-noborder-white-2.pdf](https://github.com/SwissPy/sps17/files/639216/python-summit-sticker-noborder-white-2.pdf)

**Comment by The-Compiler** [comment]
- [x] ordered! :tada:

**Comment by The-Compiler** [comment]
We have stickers!

![s2](https://cloud.githubusercontent.com/assets/625793/21381327/f0d2099c-c75a-11e6-828f-48ebbd31d4b4.jpg)

They're at HSR in my locker now.

(also, GitHub doesn't exif-rotate pictures in its preview here...)

**Comment by dbrgn** [comment]
Awesome!

**Comment by chiesax** [comment]
Can't wait...

**Comment by The-Compiler** [comment]
@dbrgn if you want some and happen to be at HSR, I left some on the coffee table (where the selecta machine is), and in the VSHSR-room - get them before they're gone! :laughing:

**Comment by ccdesales** [comment]
AFAIK stickers arrived.
