### ISSUE TITLE
Real time questions during the talk

### ISSUE THREAD

**Issue by bkarolina** [SwissPy/sps17#25]
Hi guys,

some of you i mentioned in July one product: sli.do, which I found really useful (it was used at Slovak Python Conference this year).

https://www.sli.do/features-questions

Basically, instead of asking questions after the talk you can ask question during the talk via their app. Firstly, you need to sign in with #yourhastag to the event. Then you can ask a question. As a participant you see that someone else asks the same question you have in your mind, you just vote for this question. Questions appear in the app as well as on the live screen. Then the top questions (according to the votes) will be asked.

There are four categories of the product: Basic (0€ ), Private (149€ ), Pro (249€ ), Premium (749€ ).
I think the Private option should be enough for our event. In this option you have a possibility to moderate the questions (in the case of unrelated question to the talk we can resent it).

What do you think of it?

**Comment by andrekeller** [comment]
Hi,

I like the idea. Maybe there are other tools around offering similar functionality?

**Comment by dbrgn** [comment]
I also like the idea.

Participants don't need to sign up anywhere, right?

**Comment by href** [comment]
At Frontendconf they did the same thing with a twitter hashtag. It seemed to work reasonably well.

I'm not sure I would be ready to pay for it, since 149€ is something we might want to use for other optional things (like snacks at the afterparty for example).

**Comment by dbrgn** [comment]
The free offer is probably already better than twitter hashtags.

**Comment by bkarolina** [comment]
@dbrgn no, they just need to put #eventhashtag. Free offer is also fine. As I mentioned, what I like about Private option is moderation. With free version, I just hope that no one would ask some unrelated questions.
Still, I agree free version can be better than twitter.
@href I am aware of budget limits in this, therefore I suggested it here. We can do it via twitter hashtag, or later when we would know how the budget looks like we can change our minds. Or just used free version.

**Comment by dbrgn** [comment]
Unrelated questions can be ignored by the speaker :) I think offensive questions would be the bigger problem.

**Comment by ccdesales** [comment]
Other conferences are using Telegram (Europython) or Slack (PyConUK). I definitely liked Slack, as there were different channels one could join for different topics. 

Given we have not yet covered 100% our target for sponsors, I would see ski.do as only nice to have.

**Comment by dbrgn** [comment]
No, I'm definitely against a solution where users need to sign up. Especially closed source ones.

By the way, keep in mind that our budget was created based on the assumption that there are no or very little sponsors, right? So we should already be well covered.

**Comment by href** [comment]
In this case we should create an updated budget ;)

**Comment by bkarolina** [comment]
I am new with Slack and I've first heard of Telegram right now. So I don't know what they are capable of. Can you order messages in Slack according to likes? This is something, that is done automatically in sli.do. How do you evaluate the most "wanted to-be-asked" question in Slack?

**Comment by ccdesales** [comment]
No sorting or moderation of any kind that I'm aware of. People can react and add +1 to questions, and the somebody could take the ones on top of the chat window, or the ones that seem to have more +1's

**Comment by The-Compiler** [comment]
Telegram/Slack for _talk questions_? I didn't see that at Europython, and it seems to me like we're overthinking it at this point...

**Comment by ccdesales** [comment]
Sorry I wasn't clear. I saw Telegram and Slack used as general chat in other conferences, but not for questions on the talks. I was suggesting they can use as ersatz for 150€ sli.do.

**Comment by The-Compiler** [comment]
I'll have to disagree. When I need to set up Telegram or Slack accordingly before asking a question, I'm not going to ask.

**Comment by jakeret** [comment]
As long as questions can be asked in a conventional manner I don't really mind. But frankly, this sounds a bit like overkill

**Comment by dbrgn** [comment]
The advantage that I see is that you can add a question to the list of questions as soon as you think of it. If you have to wait until the end, either you already forgot the question, or maybe you're too shy to ask in the first place. sli.do would solve that issue, and additionally provide a way to prioritize questions, avoiding the classic self-promoting-statement-disguised-as-a-question questions.

**Comment by The-Compiler** [comment]
Yeah, something you can use easily from a (mobile) browser sounds like a good idea (we should probably just write an opensource alternative to sli.do some day :wink:).

I'm not sure where the prices quoted here come from, according to https://www.sli.do/pricing we'd need to pay 199 GBP + VAT (250 CHF) for a one-time thing with over 5 question sessions.

That's definitely too much, IMHO.

What I was arguing is that Slack/Telegram are totally the wrong tool for this, however.

**Comment by dbrgn** [comment]
No, that's just necessary if you want to do many polls. What we need is "Interactive Q&A", I think. With moderation it's 149€ excl. VAT, without moderation it's free.

We could also request a free demo.

> we should probably just write an opensource alternative to sli.do some day 😉

Yep, shouldn't be all too complicated if we just need questions, voting and moderation.

**Comment by aoloe** [comment]
as far as i know, google slides has the feature...

https://support.google.com/docs/answer/6386827?co=GENIE.Platform%3DDesktop&hl=en

(i've seen it (not) used in a conference a few months ago)

personally, i find all chat & co. feature rather distracting.
it's already hard enough to get the audience to really listen to the conference...

paper planes with questions on them would be neat, though : - )

**Comment by ccdesales** [comment]
OK, I've just seem sli.do in action. My thoughts:
- I agree wit Danilo in that it can be distracting to have people write and vote for the questions during the presentation.
- If the question is not clear, it's harder to have the asker elaborate, specially because many people post as anonymous
- It feels rather impersonal
- It can be useful to moderate questions ($$), but if somebody from the audience asks directly everyone will notice if a question is ill formulated or duplicated, so it's not really bringing any value on this regard. 

I think this time we should go old school and have the people ask with the mic.

**Comment by href** [comment]
It looks to me like we're not going to do this. If you disagree, please reopen.
