### ISSUE TITLE
Invited Speaker

### ISSUE THREAD

**Issue by chiesax** [SwissPy/sps17#26]
[y/n] ?
if 'y' who?

**Comment by ccdesales** [comment]
Y

**Comment by ccdesales** [comment]
I've already mentioned and approached Brandon Rhodes. The only problem is he lives in Ohio. 

http://rhodesmill.org/brandon/

**Comment by dbrgn** [comment]
Would probably be best to discuss this on Slack, otherwise all people mentioned become publicly google-indexed :)

**Comment by ccdesales** [comment]
OK, I'll remove that last reference and open a new Slack channel.
