### ISSUE TITLE
Todos / Timeline until Conference

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#27]
Please add things I've forgotten and let me know what should be changed:

---

November
- [x] Publish Keynote speaker
- [x] Remove early bird ticket pricing

December
- [x] Decide which talks to accept
- [x] Publish talks, contact speakers
- [x] Plan talk times
- [x] Organise catering
- [x] Look for helpers
- [x] Find someone that does the videos
- [x] Order Badges (from Switzerland if not too expensive)
- [x] Order Helper Shirts (from Switzerland if not too expensive)

January
- [x] Look at venue for sponsor booths
- [x] Contact sponsors about sponsor booths
- [x] Opening / closing presentations 

February
- [x] Have speakers confirm their attendance again
- [x] Organise the helpers
- [x] Organise the registration
- [x] Organise the equipment for the conference
- [x] Print large posters for various things

**Comment by jakeret** [comment]
November
- remove early bird ticket pricing

**Comment by href** [comment]
I moved the talk publication to December since we decide it then.

**Comment by href** [comment]
I've went through the tickets and cleaned up a bit to make sure the tickets reflect the plan in here. The talks are going to be selected next week. The following jobs are unassigned:

- [Find someone to do the videos](https://github.com/SwissPy/sps17/issues/28)
- [Organise the catering / social event](https://github.com/SwissPy/sps17/issues/19)
- [Look for helpers and organise them](https://github.com/SwissPy/sps17/issues/18)

Please speak up if you can offer any help!

**Comment by chiesax** [comment]
I am in to help organizing the catering / social event...

**Comment by href** [comment]
One more month :)

**Comment by href** [comment]
We organised it all!
