### ISSUE TITLE
Technical Infrastructure

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/sps17#28]
Ticket to handle infrastructure.

- live audio
- projector
- audio recording
- video recording
- lights
- room infrastructure
- video adapters

**Comment by dbrgn** [comment]
I'd still be happy if we can find someone to take over the video recording item. I can provide introduction into the topic and help with any questions.

**Comment by href** [comment]
Didn't someone else record last year? Can we ask that person to do it again?

**Comment by dbrgn** [comment]
So far he didn't signed up. But recording won't be a big issue. I'm talking more about postprocessing. (I still didn't finish & upload the last two talks :flushed:)

**Comment by href** [comment]
Still no signup from this person? Can you ask him directly if he's interested to do it again?

**Comment by dbrgn** [comment]
Actually I don't remember his name anymore... :/

**Comment by href** [comment]
Have you checked last edition's attendees-list? https://docs.google.com/spreadsheets/d/1NjWaL2QES_4BblXxWYJgAkaB_CW26E8q21pewX45_l8/edit#gid=963330719

**Comment by dbrgn** [comment]
Found his name again in an old spreadsheet. He hasn't signed up yet.

Do we have a list of potential on-site helpers? Maybe we could ask those people first?

**Comment by href** [comment]
We have one person that's not in the association. I meant to contact her anyway, to see if she wants to be part of the association:
https://docs.google.com/spreadsheets/d/1h7zmFT1L33Wx5BAnzAepZIHGUo3yUJASSVhhPKPRa54/edit#gid=694625947

Note that this is the old signup-sheet. New signups are meant to happen through a e-mail:
http://www.python-summit.ch/pages/call-for-helpers.html

**Comment by bkarolina** [comment]
I don't know anybody who can record videos, but I can ask a friend of mine, whether she would be interested to make a postprocessing (cut of videos) if this is necessary. 
How many talks we will have? (to have an idea how much work it will be for her).

**Comment by dbrgn** [comment]
Probably around 8 again...

I had a discussion with @chiesax I think about recording audio directly, that would reduce the effort of postprocessing. I'd be willing to do it again if nobody else wants to do it.

But yes, we do need someone to watch the camera and do the recordings. It's not a difficult job though :)

**Comment by dbrgn** [comment]
I visited the HSR Aula today.

This is the room:

![img_8104](https://cloud.githubusercontent.com/assets/105168/21722546/6360e364-d42d-11e6-981c-fedca3d527ee.jpg)

There are two projectors, both 1920x1200px.

![img_8122](https://cloud.githubusercontent.com/assets/105168/21722556/6d3f87d2-d42d-11e6-9187-80c6f0105fd6.jpg)

Supported video signals are HDMI and VGA. There are two scalers below the speaker's desk:

![img_8118](https://cloud.githubusercontent.com/assets/105168/21722568/82cfbf68-d42d-11e6-9893-db7ffabee2f2.jpg)
![img_8119](https://cloud.githubusercontent.com/assets/105168/21722569/82ed05fa-d42d-11e6-9e40-9e291b3f2fdf.jpg)

If that's not enough, there's an "extension rack":

![img_8121](https://cloud.githubusercontent.com/assets/105168/21722575/8d30786c-d42d-11e6-8268-51010a3b7e30.jpg)

There are lots of adapters for different connectors. We should probably ask each speaker to let us know what connector they have on their laptop.

There are multiple on-head and hand mics available, all wireless. There's an audio mixer backstage.

Here's the multimedia rack backstage:

![img_8108](https://cloud.githubusercontent.com/assets/105168/21722612/c3b7d33a-d42d-11e6-9b00-86c566adc362.jpg)
![img_8109](https://cloud.githubusercontent.com/assets/105168/21722611/c3b7956e-d42d-11e6-973e-2b5c0246d4be.jpg)
![img_8110](https://cloud.githubusercontent.com/assets/105168/21722610/c3b72052-d42d-11e6-9918-b5702dbf1360.jpg)

On the bottom right you can see an audio output. That can be used for recording.

We can also borrow a video camera again (Sony HDR-CX900E). It has a 3.5mm jack input. We can then send the audio mix directly to the camera. I'd suggest to use a splitter and to record the audio signal using a laptop too, as backup.

I think that should cover all our needs :)

**Comment by chiesax** [comment]
What is the price to borrow the video camera? I am not sure we have included this in the budget...

**Comment by dbrgn** [comment]
Free :)

**Comment by chiesax** [comment]
I like this price!
