### ISSUE TITLE
choose bank for sps association account

### ISSUE THREAD

**Issue by chiesax** [SwissPy/sps17#3]
Need to call some swiss banks and have a list of offers to be evaluated. 

Ubs, credit suisse, migros and coop banks, post, zkb...

With zkb we are then bound to canton zurich, but we should easily find someone located there if needed.

**Comment by dbrgn** [comment]
Bank Linth is free for associations. Don't know about others.

I like https://www.abs.ch/, but I'm not sure about fees for associations.

**Comment by chiesax** [comment]
I just see a problem with Bank Linth because it is a local bank (https://www.banklinth.ch/de/privatkunden/kontakt/standortfinder)

**Since we are a Swiss (as opposed to Cantonal) association, we should better find a Bank which is easily accessible in the whole country** (and this excludes Cantonal Banks and Reiffeisen banks). 

I have looked at the PostFinance offer for associations (https://www.postfinance.ch/en/biz/prod/acc/club/detail.html), :
- 60 CHF/year fees (which we can easily cover with the membership fees)
- two bancomat cards included,
- e-banking,
- desks granularly located in the whole country,
- to open the account, President + one  comittee member must go to a PostFinance desk with the documentation and identity cards.

Called UBS Neuchâtel to get some info: as soon as they understood we are a making up a small association they put me on hold. After five minutes of waiting I decided to quit. (and I did not manage to gather information about "Associations Accounts" on UBS or Credit Suisse on their internet sites)

ABS likes associations (https://www.abs.ch/de/online-schalter/eroeffnen-beantragen/konto-eroeffnen/einlagekonto-eroeffnen/):
- 36 CHF/year
- e-banking,
- desks in Lausanne, Olten, Zurich, Geneva,
- cards?
- apparently the opening of the account may be handled by mail

**Comment by dbrgn** [comment]
>  just see a problem with Bank Linth because it is a local bank 

Yes, I agree. I just wanted to point out that some banks offer free accounts.

**Comment by href** [comment]
I copied this issue over to the new SPSA repository that's meant for event-independent business.
