### ISSUE TITLE
Setup Swissmadesoftware Promotion

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#30]
Swissmadesoftware will promote our event on their website and they will add our event to their list of partners: https://www.swissmadesoftware.org/en/home/partners.html

To do this we need to define a rebate code to the registration form, checked by the registration team (@chiesax and @andrekeller). This rebate code keeps the price at the early-bird level after the jump to the post-early-bird price.

In addition we need to fill out a template with some information. The bulk of the work here is writing a short description for the partner site (up to 300 characters, German and English) as well as a description of the Summit 2017 (two paragraphs, 800-1000 characters, German and English):

https://docs.google.com/document/d/1ZgK7JvR3NIvsxWxUTYtQWK4mW2efudmCr6Iubwt3Css/edit

This needs to happen shortly after we've confirmed the program and put it online.

**Comment by href** [comment]
FYI we need to finish this document by Friday evening. At the same time we want to be able to accept the rebate in the registration form (by then we switch to post-early bird). The mailer goes out next week, so we might see some more users thanks to this.

The rebate code will be defined in the chat, not publicly.

**Comment by jakeret** [comment]
I'll have a go tomorrow evening and will send you the draft. 
But first I need access to the document ;)

**Comment by href** [comment]
Did you get it now? I think I didn't have the right Google ID for you on the memberslist.

**Comment by jakeret** [comment]
All good now. Thanks

On Dec 8, 2016 10:10 PM, "Denis Krienbühl" <notifications@github.com> wrote:

Did you get it now? I think I didn't have the right Google ID for you on
the memberslist.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SwissPy/sps17/issues/30#issuecomment-265856448>, or mute
the thread

**Comment by jakeret** [comment]
Done. Can you check the text bits in red? How much reduction do the members get 33 or 66%?

**Comment by href** [comment]
Well done, thanks! And you're correct, it's 33%.

I'll pass this on to swissmadesoftware tomorrow.
