### ISSUE TITLE
Create program

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/sps17#31]
We can document here the steps until a program is defined.

**Comment by ccdesales** [comment]
The program from last year, for reference:

> 
> 08:30 - 09:00 Registration (open until 09:15)
> 09:00 - 09:15 Welcome
> 09:20 - 09:50 Talk 1: Tom Ron – Python's guide to the galaxy
> 09:50 - 10:30 Talk 2: Dave Halter – API Design Is Hard
> 10:30 - 11:00 Coffee break
> 11:00 - 11:40 Talk 3: Armin Rigo – CFFI: call C from Python
> 11:40 - 12:20 Talk 4: Martin Christen – 3D Computer Graphics with Python
> 12:20 - 13:40 Lunch
> 13:40 - 14:30 Talk 5: Matthieu Amiguet – Charming Snake: Python for Live Music
> 14:30 - 15:10 Talk 6: Chihway Chang – Coding/Decoding the Cosmos: Python Applications in Astrophysics
> 15:10 - 15:40 Coffee break
> 15:40 - 16:10 Talk 7: Michael Rüegg – Scrapy and Elasticsearch: powerful web scraping and searching with Python
> 16:10 - 16:40 Talk 8: Jacinda Shelly – Getting Started with IPython
> 16:40 - 17:10 Talk 9: Florian Bruhin – pytest: rapid simple testing
> 17:10 - 17:20 Closing

**Comment by href** [comment]
Just a reminder: this year we have one slot less as we already have a keynote speaker.
