### ISSUE TITLE
Setup Call For Posters

### ISSUE THREAD

**Issue by chiesax** [SwissPy/sps17#32]
During the last meeting we have decided to setup a call for posters. At the HSR Aula, there is room for approximately 40 posters. The posters will be placed close to the coffee / social event, which will offer the possibility to trigger interesting discussions during the breaks!

**Comment by chiesax** [comment]
How it should work:
- we set up a google form to register the posters,
- we add a comment on the registration form about the size of any company logos on the posters (I suggest the logos must not take more than 5% surface of the A0 poster, otherwise they may be rejected at the conference)
- we just verify that the abstract has something to do with python, but we do not make a proper selection as for the talks
- just before the conference, we send a bulk confirmation mail to all people that have submitted a poster

**Comment by chiesax** [comment]
(just before the conference --> lets say two weeks in advance)

**Comment by href** [comment]
Note that we might want to reserve a few of the available slots for our own posters, like the program or the job-board.

**Comment by chiesax** [comment]
30 posters then?

**Comment by chiesax** [comment]
Here the registration form. I'll publish it on the site this week end if nobody disagrees.

https://docs.google.com/forms/d/1XriMP-XCvznIbja2A0szd6RIwGZu-LVxxtyyTV4ykS0/edit

**Comment by href** [comment]
How is it going with the call for posters? We need the posters ready for printing no later than on the 13th of February, so @sfkeller can print them in time.
