### ISSUE TITLE
Prepare Sponsor Booths

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#33]
Our platinum sponsor is asking how the booth situation will look like. They want to know where they can put the booth, how big it is and so on. Ideally we could provide some kind of floor plan.

In any case we are going to have a maximum of two booths (Seantis won't be doing one) and I would imagine that we put them inside the auditorium. The spots should be prominent (they are paying for the privilege after all) and they have to fit together with the posters. I'm guessing we should provide at least some kind of table as well as chairs.

@sfkeller Is the auditorium the right place to have sponsor booths and do you have some kind of floor plan for the auditorium?

**Comment by The-Compiler** [comment]
Does this help? 
[Verwaltungsgebaeude_OG.pdf](https://github.com/SwissPy/sps17/files/652797/Verwaltungsgebaeude_OG.pdf)

**Comment by href** [comment]
It's a start. Though I won't presume to know where to pot the booths just from looking at this plan. Maybe people more familiar with the location can weigh in.

**Comment by dbrgn** [comment]
Maybe here, next to the wall?

![plan](https://cloud.githubusercontent.com/assets/105168/21216343/768729be-c2a6-11e6-8c94-64f1921a7e4b.png)

**Comment by href** [comment]
Should we put the booth(s) and the poster together or on opposite sides of the room - or a mix of the two? The catering is outside, right?

What I want to avoid is that the booth(s) are something nobody cares to go to. So they should be more prominent and central than the posters imho.

**Comment by sfkeller** [comment]
@dbrgn That's what I would have suggested too at the castle side, there's enough space there.
The reception / registration would be in front of the first / main door.
This way when people are arriving, they come up the stairs, make registration, then enter the Aula.
At the lake side there's space for posters - and also for stand-up tables.
The catering area with buffet tables is at "4.100a Einganghalle" longside.

**Comment by href** [comment]
Does this make sense?
![screenshot of sketch 16-12-16 10-18-50](https://cloud.githubusercontent.com/assets/273163/21257538/1cbabdbe-c379-11e6-9c83-2127f2df8167.png)

**Comment by sfkeller** [comment]
Looks good to me.

**Comment by dbrgn** [comment]
Yes! Thanks for doing it in a nicer way than me :smile:

**Comment by href** [comment]
A gold sponsor would like to have one or more high tables (stehtische). The other probably a normal table and chairs. That shouldn't be a problem, right?

**Comment by href** [comment]
Oh and I assume electricity and WiFi is a given, right?

**Comment by sfkeller** [comment]
Stehtische and normal tables are no problem.
Electricity is given.
WiFi also but needs to be announced before hand.

**Comment by href** [comment]
Okay, thanks. If you could announce the WIFI like you did last year that would be great.

**Comment by dbrgn** [comment]
FYI, this is the registration area:

![img_8098-pano](https://cloud.githubusercontent.com/assets/105168/21722491/2dba22f2-d42d-11e6-903d-2b88045d0f19.jpg)

And here where I'm standing we'll put the sponsor booths:

![img_8105](https://cloud.githubusercontent.com/assets/105168/21722507/3c1210da-d42d-11e6-9fcf-35f0d8947798.jpg)
