### ISSUE TITLE
Lanyards / Badge Holder

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#34]
We need to order the lanyards/badge holders this week if we want to be reasonably sure we actually get them on time. Since last time it went rather badly when we ordered them from Germany I suggest we go with a Swiss shop.

The cheapest I could find was http://www.easyid.ch

This is what it would cost us, if we get 250 pieces:
![screenshot of safari 02-01-17 11-17-23](https://cloud.githubusercontent.com/assets/273163/21587479/38d438ec-d0dd-11e6-9768-8102267086c6.png)

I contacted them already and they got all this in stock, so we would get it quite quickly.

Other shops operate around the same price, with some shops being more expensive. Printing is out of the question at this time, for that we are too late (not to mention that it's more expensive).

What I need to know:

- How many should I order?
- Are there any objections to the shop/product?
- Can I send the order to you @dbrgn?
- Can we adjust the budget accordingly (300.- is a bit on the low side) @chiesax?

Let me know by the end of the week, so we can cross this item off our todo-list.

**Comment by jakeret** [comment]
Last year we received the ribbons (Bändel) from a sponsor, right? Any chance we could get some this year as well?
As for the numbers, 250 sounds about right

**Comment by href** [comment]
They actually sponsored the ribbons with the Django CMS logo on it. So it would have to be another sponsored logo if we went that route, to be fair to our existing sponsors.

So we could technically ask our platinum sponsor if they have any ribbons to provide us with, but I'd rather keep them out of it since we can just order these without any kind of coordination with the sponsor. Plus without logo they are reusable.

**Comment by dbrgn** [comment]
@href yes you can send the order to me.

It's quite expensive, but I guess we should go with this shop for now, and could order from China next time. Just a quick example: https://www.alibaba.com/product-detail/OEM-Id-card-rope-langyards-neck_60355295339.html?spm=a2700.7724838.0.0.aiXFKx (I think this includes printing.)

**Comment by href** [comment]
Yeah, it occurred to me today that we should've done this way earlier.

**Comment by chiesax** [comment]
What about poster printing? We had a budget of 200 CHF, but this must be much less since HSR is taking care of that right?

**Comment by chiesax** [comment]
So I would say if we can decrease the poster budget to 100 chf, and since t shirts will be approx 100 chf cheaper, then I am okay with this.

**Comment by chiesax** [comment]
So I would say if we can decrease the poster budget to 100 chf, and since t shirts will be approx 100 chf cheaper, then I am okay with this.

**Comment by href** [comment]
Yeah, the poster printing is not going to cost us anything from what I understand. HSR is basically sponsoring that. I'm also looking at a few other shops for the lanyard itself, which I think we can get cheaper even in Switzerland.

**Comment by href** [comment]
Alright, I got the lanyards somewhat cheaper (the price I posted here was even higher since it excluded VAT). All in all the costs are 442.80. 

@dbrgn Let me know when you get any packages (you should get two all in all) and be sure to check if the resulting lanyard/sleeve combination is what we need.

The package with the sleeves might also include the bill, if they don't decide to switch to pre-paid. If so, you would have to give the bill to @chiesax.

The lanyards I'll pay tonight through online-banking.

Next time we do this via China. I doubt that'll be any harder actually. The online shops I used are atrocious :)

**Comment by dbrgn** [comment]
Sleeves arrived :)

**Comment by ccdesales** [comment]
We have the sleeves and the lanyards. I think now we only need the following:

- [ ] Cards for people to write the name on.
- [ ] Markers to write

I can't remember how we did last year. 

Should I buy the cards and markers?  I guess white cards should do, and assume we are not printing anything on them, unless somebody has the time and tonner for that.

@dbrgn What size do the cards need to be to fit into the sleeves?

**Comment by href** [comment]
> Should I buy the cards and markers? I guess white cards should do, and assume we are not printing anything on them, unless somebody has the time and tonner for that.

Actually last year we had a printed batch:
![screenshot of finder 19-01-17 18-33-50](https://cloud.githubusercontent.com/assets/273163/22117872/e63ac2da-de75-11e6-96bb-36bbb6226d2c.png)

I would assume we do this again, assuming that @sfkeller will help us out again.

In any case, +1 on the markers.

**Comment by ccdesales** [comment]
@href the design needs to be updated, I assume you have the original. Is this something you can tackle?

**Comment by href** [comment]
Yeah, no problem. It's just a small update. I have to do the same for the job-board posters.
