### ISSUE TITLE
Change the Program so Lunch can Start at 12:45

### ISSUE THREAD

**Issue by href** [SwissPy/sps17#36]
To accomodate all the people for lunch we need to move the program slightly to have lunch starting at 12:45. Otherwise the canteen might be a bit overwhelmed (it houses 250).

Any suggestions on how we should move things around?

**Comment by chiesax** [comment]
Just move Dave Halter in the morning?

**Comment by href** [comment]
Okay, this would result in this swap:

12:10-12:40 - Python is Weird by Dave Halter
12:40-14:00 - Lunch

If there are no objections we can change this and let Dave know.

**Comment by href** [comment]
I changed the program accordingly:
http://www.python-summit.ch/pages/program.html

@bkarolina Can you let Dave know that his schedule changed?

**Comment by bkarolina** [comment]
@href yes, I let him know. Sorry for delayed reply, I was on short vacation.

**Comment by ccdesales** [comment]
The program has been changed and Dave was notified.
