### ISSUE TITLE
Create Call for Proposals

### ISSUE THREAD

**Issue by cdesales** [SwissPy/sps17#7]
I'd let it run till End of October 2016.

**Comment by cdesales** [comment]
The Form:

https://docs.google.com/forms/d/1XsBMNB__Z1mzX7Ob6DbuFEHy1QpKAb4oQtIAF7XnF1g/edit?uiv=1

**Comment by dbrgn** [comment]
Form looks good!

**Comment by cdesales** [comment]
Done, please validate at the website, then we can promote it.

**Comment by href** [comment]
Looks all good to me!

**Comment by jakeret** [comment]
I think it would be good to have a reference to the call for proposal on the main site.

**Comment by ccdesales** [comment]
> I think it would be good to have a reference to the call for proposal on the main site.

Done
