### ISSUE TITLE
Define ticket price for early bird

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/sps17#9]
We can either make a guess, or try to come up with a draft of the budget.

I'm still for having cheap tickets.

I'd also say that confirmation of attendance will be sent once payment is done, in an attempt to reduce no-shows. This depends on us finishing the paperwork for the SPS bank account.

**Comment by bkarolina** [comment]
I agree that the confirmation of attendance should be sent after the payment is done.

**Comment by dbrgn** [comment]
I'd suggest to have different prices for personal and company tickets.

My idea would be to have company tickets at 50-80 CHF and personal tickets at 20 CHF. Last year's 10 CHF did not even cover all costs. But before we can do that, we have to get a list of all expenses.

**Comment by chiesax** [comment]
We could say for instance that until 1 month before the conference registration is only possible via pre-payement for 20CHF. Then we open to on-site payement, with the risk people is not showing up, and increase the price to 30 CHF or 40 CHF.

**Comment by ccdesales** [comment]
If I recall correctly we've agreed to have the following prices:
- 20 CHF for private early bird tickets
- 50 CHF for company funded early bird tickets
